# Image preprocessing function

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import os
import cv2
import numpy as np

def deskew(img, max_angle_threshold=1.5):
    coords = np.column_stack(np.where(img < 255))
    if coords.shape[0] == 0:
        return img

    mean, eigenvectors = cv2.PCACompute(coords.astype(np.float32), mean=np.array([]))
    angle = np.arctan2(eigenvectors[0, 1], eigenvectors[0, 0]) * 180.0 / np.pi

    # ✅ Ignore angles that are too large (PCA mistake)
    if abs(angle) < max_angle_threshold:
        return img

    # ✅ If PCA thinks text is vertical, skip rotation
    if abs(angle) > 45:
        return img

    (h, w) = img.shape
    center = (w // 2, h // 2)

    M = cv2.getRotationMatrix2D(center, angle, 1.0)
    abs_cos = abs(M[0, 0])
    abs_sin = abs(M[0, 1])
    new_w = int(h * abs_sin + w * abs_cos)
    new_h = int(h * abs_cos + w * abs_sin)

    M[0, 2] += (new_w / 2) - center[0]
    M[1, 2] += (new_h / 2) - center[1]

    rotated = cv2.warpAffine(img, M, (new_w, new_h),
                              flags=cv2.INTER_CUBIC,
                              borderMode=cv2.BORDER_CONSTANT,
                              borderValue=255)

    # ✅ Force horizontal layout
    if rotated.shape[0] > rotated.shape[1]:
        rotated = cv2.rotate(rotated, cv2.ROTATE_90_CLOCKWISE)

    return rotated

def preprocess_image_for_ocr(
    image_path,
    save_path=None,
    binarize=True,
    use_bilateral=True
):
    img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        raise FileNotFoundError(f"Image not found: {image_path}")

    # === Noise removal ===
    if use_bilateral:
        img = cv2.bilateralFilter(img, d=5, sigmaColor=75, sigmaSpace=75)
    else:
        img = cv2.GaussianBlur(img, (3, 3), 0)

    # === Padding before deskew ===
    img = cv2.copyMakeBorder(img, 20, 20, 20, 20, cv2.BORDER_CONSTANT, value=255)

    # === Deskew ===
    img = deskew(img)

    # === Binarization (no inversion) ===
    if binarize:
        img = cv2.adaptiveThreshold(
            img, 255,
            cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
            cv2.THRESH_BINARY,
            31, 10
        )

    # Fix orientation if needed
    #if img.shape[1] > img.shape[0]:
        #img = cv2.rotate(img, cv2.ROTATE_90_COUNTERCLOCKWISE)

    # === Normalize & format ===
    img_norm = img.astype(np.float32) / 255.0
    img_norm = np.expand_dims(img_norm, axis=0)  # [1, H, W]

    # === Save output ===
    if save_path:
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        cv2.imwrite(save_path, img)

    return img_norm

def preprocess_folder(
    input_folder,
    output_folder,
    binarize=True,
    use_bilateral=True,
    out_ext=".png",
    verbose=True
):
    os.makedirs(output_folder, exist_ok=True)

    for fname in os.listdir(input_folder):
        if not fname.lower().endswith((".png", ".jpg", ".jpeg")):
            continue

        input_path = os.path.join(input_folder, fname)
        output_name = os.path.splitext(fname)[0] + out_ext
        output_path = os.path.join(output_folder, output_name)

        try:
            preprocess_image_for_ocr(
                image_path=input_path,
                save_path=output_path,
                binarize=binarize,
                use_bilateral=use_bilateral
            )
            if verbose:
                print(f"✅ Processed and saved: {output_name}")
        except Exception as e:
            print(f"❌ Failed on {fname}: {e}")

## Copying the images to one folder for faster access

In [3]:
import os
import shutil

def copy_images_to_single_folder(input_folder, output_folder, extensions=(".png", ".jpg", ".jpeg")):
    """
    Copies all images from subfolders in `input_folder` to `output_folder`.
    Keeps only files with specified extensions.
    Does not modify or process the images.
    """
    os.makedirs(output_folder, exist_ok=True)
    count = 0

    for root, _, files in os.walk(input_folder):
        for file in files:
            if file.lower().endswith(extensions):
                src_path = os.path.join(root, file)
                dst_path = os.path.join(output_folder, file)

                # Avoid overwrite by renaming if needed
                base, ext = os.path.splitext(file)
                counter = 1
                while os.path.exists(dst_path):
                    dst_path = os.path.join(output_folder, f"{base}_{counter}{ext}")
                    counter += 1

                shutil.copy2(src_path, dst_path)
                count += 1
                print(f"📁 Copied: {dst_path}")

    print(f"\n✅ Finished! {count} images copied to: {output_folder}")

In [7]:
copy_images_to_single_folder(
    input_folder="/content/drive/MyDrive/ComputerVision/sentences",
    output_folder="/content/drive/MyDrive/ComputerVision/sentences_all/"
)

Streaming output truncated to the last 5000 lines.
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-008-s02-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-008-s01-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-008-s00-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-008-s01-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-008-s00-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-008-s04-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-008-s04-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-008-s04-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-018-s00-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-018-s00-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-018-s00-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-018-s00-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-018-s00-05.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-018-s00-04.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-018-s01-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-018-s01-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-018-s01-04.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-018-s01-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-018-s01-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-018-s02-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-018-s02-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-014-s00-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-014-s00-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-014-s01-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-014-s01-04.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-014-s00-05.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-014-s01-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-014-s00-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-014-s00-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-014-s01-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-014-s01-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-014-s00-04.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-014-s02-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-014-s02-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-014-s02-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-000-s01-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-000-s02-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-000-s02-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-000-s03-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-000-s00-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-000-s02-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-000-s00-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-000-s02-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-000-s01-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-000-s00-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-000-s03-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-000-s03-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-000-s03-04.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-000-s03-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-056-s00-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-056-s01-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-056-s00-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-056-s00-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-056-s00-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-056-s01-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-056-s01-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-056-s01-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-056-s02-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-056-s01-05.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-056-s02-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/j06-056-s01-04.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/h05-012-s01-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/h05-012-s01-04.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/h05-012-s00-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/h05-012-s00-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/h05-012-s01-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/h05-012-s01-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/h05-012-s01-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/h05-012-s00-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-089-s00-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-089-s00-04.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-089-s00-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-089-s00-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-089-s00-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-089-s01-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-089-s00-05.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-089-s01-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-089-s00-06.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-089-s01-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-089-s01-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-081-s00-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-081-s01-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-081-s01-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-081-s01-04.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-081-s02-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-081-s02-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-081-s02-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-081-s00-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-081-s00-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-081-s02-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-081-s01-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-081-s01-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-027-s00-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-027-s01-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-027-s01-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-027-s01-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-027-s02-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-027-s02-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-027-s00-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-027-s02-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-019-s00-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-019-s00-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-019-s00-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-019-s01-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-019-s01-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-019-s02-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-019-s00-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-019-s02-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-019-s02-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-019-s02-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-092-s00-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-092-s01-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-092-s00-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-092-s00-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-092-s01-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-092-s01-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-092-s01-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-092-s02-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-092-s01-04.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-092-s02-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-092-s02-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-092-s02-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-092-s02-04.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-003-s00-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-003-s00-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-003-s00-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-003-s00-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-003-s01-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-003-s01-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-003-s01-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-003-s01-04.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-003-s01-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-066-s00-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-066-s00-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-066-s01-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-066-s01-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-066-s01-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-066-s01-04.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-066-s01-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-066-s00-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-066-s01-06.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-066-s01-05.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-010-s00-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-010-s00-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-010-s01-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-010-s02-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-010-s01-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-010-s00-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-010-s02-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-010-s01-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-010-s03-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-010-s03-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-010-s02-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-010-s03-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-059-s00-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-059-s00-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-059-s01-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-059-s01-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-059-s02-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-059-s00-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-059-s02-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-059-s02-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-059-s02-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-059-s02-04.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-035-s00-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-035-s00-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-035-s01-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-035-s01-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-035-s01-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-035-s01-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-035-s01-04.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-035-s01-05.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-035-s02-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-035-s02-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-035-s02-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-035-s00-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-043-s02-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-043-s02-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-043-s00-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-043-s00-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-043-s01-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-043-s01-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-043-s01-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-043-s02-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-043-s02-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-043-s02-04.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-043-s01-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-050-s00-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-050-s00-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-050-s01-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-050-s01-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-050-s02-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-050-s02-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-050-s01-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-050-s00-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-050-s02-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-072-s00-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-072-s00-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-072-s00-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-072-s01-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-072-s01-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-072-s00-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-072-s01-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-072-s01-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-072-s02-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-072-s03-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-072-s03-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-072-s02-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-072-s03-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-031-s00-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-031-s00-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-031-s01-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-031-s00-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-031-s01-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-031-s00-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-031-s01-04.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-031-s02-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-031-s01-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-031-s01-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-031-s02-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-031-s02-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-085-s00-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-085-s00-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-085-s00-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-085-s00-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-085-s01-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-085-s01-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-085-s01-04.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-085-s01-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-085-s01-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-085-s02-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-085-s02-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-069-s00-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-069-s00-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-069-s01-01.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-069-s00-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-069-s00-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-069-s01-00.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-069-s01-02.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-069-s01-05.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-069-s01-03.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-069-s01-04.png
📁 Copied: /content/drive/MyDrive/ComputerVision/sentences_all2/a04-023-s00-01.png

## Reading the Data from Sentence

### creating metadata from sentence

In [8]:
import os
import csv
import concurrent.futures

def scan_images_multithreaded(image_base_folder):
    """
    Scans base and subfolders, returns {form_id: full_image_path}
    Supports .png, .jpg, .jpeg (case insensitive)
    """
    all_images = {}

    def scan_folder(folder):
        sub_images = {}
        for root, _, files in os.walk(folder):
            for file in files:
                if file.lower().endswith(('.jpeg', '.jpg', '.png')):
                    form_id = os.path.splitext(file)[0].lower()
                    sub_images[form_id] = os.path.join(root, file)
        return sub_images

    # ✅ Scan base folder + any subdirectories
    scan_targets = [image_base_folder] + [
        os.path.join(image_base_folder, sub)
        for sub in os.listdir(image_base_folder)
        if os.path.isdir(os.path.join(image_base_folder, sub))
    ]

    with concurrent.futures.ThreadPoolExecutor() as executor:
        futures = [executor.submit(scan_folder, folder) for folder in scan_targets]
        for future in concurrent.futures.as_completed(futures):
            all_images.update(future.result())

    return all_images

def create_metadata_from_sentences(sentence_txt_path, image_base_folder, output_csv_path):
    """
    Parses sentences.txt and builds a metadata CSV with:
    [form_id, image_path, printed_transcription]
    Uses multithreaded image scanning.
    """
    print("\U0001F50D Scanning image folders...")
    image_paths = scan_images_multithreaded(image_base_folder)
    print(f"✅ Found {len(image_paths)} image files")

    dataset = []

    with open(sentence_txt_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue

            parts = line.split()
            if len(parts) < 9:
                continue  # malformed line

            form_id = parts[0].lower()  # normalize
            text_tokens = parts[8:]
            clean_tokens = [t for t in text_tokens if not t.isdigit()]
            text = " ".join(clean_tokens).replace("|", " ")

            if form_id in image_paths:
                dataset.append([form_id, image_paths[form_id], text])
            else:
                print(f"⚠️ Image not found for: {form_id}")

    # Save to CSV
    with open(output_csv_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["form_id", "image_path", "transcription"])
        writer.writerows(dataset)

    print(f"✅ Sentence metadata saved to: {output_csv_path}")

In [9]:
create_metadata_from_sentences(
    sentence_txt_path="/content/drive/MyDrive/ComputerVision/ascii/sentences.txt",
    image_base_folder="/content/drive/MyDrive/ComputerVision/sentences_all/",
    output_csv_path="/content/drive/MyDrive/ComputerVision/VisionSpeak/Sentence_Metadata.csv"
)

🔍 Scanning image folders...
✅ Found 16873 image files
✅ Sentence metadata saved to: /content/drive/MyDrive/ComputerVision/VisionSpeak/Sentence_Metadata.csv

## Preprocessing the sentences images

### some issue with preprocessing funcrion

In [10]:
preprocess_folder(
    input_folder="/content/drive/MyDrive/ComputerVision/sentences_all/",
    output_folder="/content/drive/MyDrive/ComputerVision/sentences_all/",
    binarize=True,
    use_bilateral=True
)

Streaming output truncated to the last 5000 lines.
✅ Processed and saved: j06-008-s03-02.png
✅ Processed and saved: j06-008-s00-02.png
✅ Processed and saved: j06-008-s02-00.png
✅ Processed and saved: j06-008-s01-01.png
✅ Processed and saved: j06-008-s00-01.png
✅ Processed and saved: j06-008-s01-00.png
✅ Processed and saved: j06-008-s00-00.png
✅ Processed and saved: j06-008-s04-00.png
✅ Processed and saved: j06-008-s04-01.png
✅ Processed and saved: j06-008-s04-02.png
✅ Processed and saved: j06-018-s00-03.png
✅ Processed and saved: j06-018-s00-02.png
✅ Processed and saved: j06-018-s00-00.png
✅ Processed and saved: j06-018-s00-01.png
✅ Processed and saved: j06-018-s00-05.png
✅ Processed and saved: j06-018-s00-04.png
✅ Processed and saved: j06-018-s01-01.png
✅ Processed and saved: j06-018-s01-02.png
✅ Processed and saved: j06-018-s01-04.png
✅ Processed and saved: j06-018-s01-00.png
✅ Processed and saved: j06-018-s01-03.png
✅ Processed and saved: j06-018-s02-00.png
✅ Processed and saved: j06-018-s02-01.png
✅ Processed and saved: j06-014-s00-01.png
✅ Processed and saved: j06-014-s00-00.png
✅ Processed and saved: j06-014-s01-03.png
✅ Processed and saved: j06-014-s01-04.png
✅ Processed and saved: j06-014-s00-05.png
✅ Processed and saved: j06-014-s01-02.png
✅ Processed and saved: j06-014-s00-03.png
✅ Processed and saved: j06-014-s00-02.png
✅ Processed and saved: j06-014-s01-01.png
✅ Processed and saved: j06-014-s01-00.png
✅ Processed and saved: j06-014-s00-04.png
✅ Processed and saved: j06-014-s02-00.png
✅ Processed and saved: j06-014-s02-01.png
✅ Processed and saved: j06-014-s02-02.png
✅ Processed and saved: j06-000-s01-01.png
✅ Processed and saved: j06-000-s02-02.png
✅ Processed and saved: j06-000-s02-03.png
✅ Processed and saved: j06-000-s03-00.png
✅ Processed and saved: j06-000-s00-00.png
✅ Processed and saved: j06-000-s02-01.png
✅ Processed and saved: j06-000-s00-01.png
✅ Processed and saved: j06-000-s02-00.png
✅ Processed and saved: j06-000-s01-00.png
✅ Processed and saved: j06-000-s00-02.png
✅ Processed and saved: j06-000-s03-01.png
✅ Processed and saved: j06-000-s03-02.png
✅ Processed and saved: j06-000-s03-04.png
✅ Processed and saved: j06-000-s03-03.png
✅ Processed and saved: j06-056-s00-01.png
✅ Processed and saved: j06-056-s01-00.png
✅ Processed and saved: j06-056-s00-00.png
✅ Processed and saved: j06-056-s00-02.png
✅ Processed and saved: j06-056-s00-03.png
✅ Processed and saved: j06-056-s01-01.png
✅ Processed and saved: j06-056-s01-02.png
✅ Processed and saved: j06-056-s01-03.png
✅ Processed and saved: j06-056-s02-01.png
✅ Processed and saved: j06-056-s01-05.png
✅ Processed and saved: j06-056-s02-00.png
✅ Processed and saved: j06-056-s01-04.png
✅ Processed and saved: h05-012-s01-03.png
✅ Processed and saved: h05-012-s01-04.png
✅ Processed and saved: h05-012-s00-00.png
✅ Processed and saved: h05-012-s00-01.png
✅ Processed and saved: h05-012-s01-02.png
✅ Processed and saved: h05-012-s01-00.png
✅ Processed and saved: h05-012-s01-01.png
✅ Processed and saved: h05-012-s00-02.png
✅ Processed and saved: a04-089-s00-01.png
✅ Processed and saved: a04-089-s00-04.png
✅ Processed and saved: a04-089-s00-03.png
✅ Processed and saved: a04-089-s00-02.png
✅ Processed and saved: a04-089-s00-00.png
✅ Processed and saved: a04-089-s01-01.png
✅ Processed and saved: a04-089-s00-05.png
✅ Processed and saved: a04-089-s01-02.png
✅ Processed and saved: a04-089-s00-06.png
✅ Processed and saved: a04-089-s01-00.png
✅ Processed and saved: a04-089-s01-03.png
✅ Processed and saved: a04-081-s00-01.png
✅ Processed and saved: a04-081-s01-02.png
✅ Processed and saved: a04-081-s01-03.png
✅ Processed and saved: a04-081-s01-04.png
✅ Processed and saved: a04-081-s02-00.png
✅ Processed and saved: a04-081-s02-01.png
✅ Processed and saved: a04-081-s02-02.png
✅ Processed and saved: a04-081-s00-02.png
✅ Processed and saved: a04-081-s00-00.png
✅ Processed and saved: a04-081-s02-03.png
✅ Processed and saved: a04-081-s01-00.png
✅ Processed and saved: a04-081-s01-01.png
✅ Processed and saved: a04-027-s00-01.png
✅ Processed and saved: a04-027-s01-00.png
✅ Processed and saved: a04-027-s01-01.png
✅ Processed and saved: a04-027-s01-02.png
✅ Processed and saved: a04-027-s02-00.png
✅ Processed and saved: a04-027-s02-01.png
✅ Processed and saved: a04-027-s00-00.png
✅ Processed and saved: a04-027-s02-02.png
✅ Processed and saved: a04-019-s00-01.png
✅ Processed and saved: a04-019-s00-00.png
✅ Processed and saved: a04-019-s00-02.png
✅ Processed and saved: a04-019-s01-00.png
✅ Processed and saved: a04-019-s01-01.png
✅ Processed and saved: a04-019-s02-02.png
✅ Processed and saved: a04-019-s00-03.png
✅ Processed and saved: a04-019-s02-00.png
✅ Processed and saved: a04-019-s02-01.png
✅ Processed and saved: a04-019-s02-03.png
✅ Processed and saved: a04-092-s00-00.png
✅ Processed and saved: a04-092-s01-02.png
✅ Processed and saved: a04-092-s00-02.png
✅ Processed and saved: a04-092-s00-01.png
✅ Processed and saved: a04-092-s01-00.png
✅ Processed and saved: a04-092-s01-01.png
✅ Processed and saved: a04-092-s01-03.png
✅ Processed and saved: a04-092-s02-00.png
✅ Processed and saved: a04-092-s01-04.png
✅ Processed and saved: a04-092-s02-01.png
✅ Processed and saved: a04-092-s02-03.png
✅ Processed and saved: a04-092-s02-02.png
✅ Processed and saved: a04-092-s02-04.png
✅ Processed and saved: a04-003-s00-00.png
✅ Processed and saved: a04-003-s00-01.png
✅ Processed and saved: a04-003-s00-02.png
✅ Processed and saved: a04-003-s00-03.png
✅ Processed and saved: a04-003-s01-01.png
✅ Processed and saved: a04-003-s01-00.png
✅ Processed and saved: a04-003-s01-03.png
✅ Processed and saved: a04-003-s01-04.png
✅ Processed and saved: a04-003-s01-02.png
✅ Processed and saved: a04-066-s00-01.png
✅ Processed and saved: a04-066-s00-02.png
✅ Processed and saved: a04-066-s01-00.png
✅ Processed and saved: a04-066-s01-01.png
✅ Processed and saved: a04-066-s01-02.png
✅ Processed and saved: a04-066-s01-04.png
✅ Processed and saved: a04-066-s01-03.png
✅ Processed and saved: a04-066-s00-00.png
✅ Processed and saved: a04-066-s01-06.png
✅ Processed and saved: a04-066-s01-05.png
✅ Processed and saved: a04-010-s00-01.png
✅ Processed and saved: a04-010-s00-02.png
✅ Processed and saved: a04-010-s01-01.png
✅ Processed and saved: a04-010-s02-01.png
✅ Processed and saved: a04-010-s01-02.png
✅ Processed and saved: a04-010-s00-00.png
✅ Processed and saved: a04-010-s02-00.png
✅ Processed and saved: a04-010-s01-00.png
✅ Processed and saved: a04-010-s03-00.png
✅ Processed and saved: a04-010-s03-01.png
✅ Processed and saved: a04-010-s02-02.png
✅ Processed and saved: a04-010-s03-02.png
✅ Processed and saved: a04-059-s00-00.png
✅ Processed and saved: a04-059-s00-01.png
✅ Processed and saved: a04-059-s01-00.png
✅ Processed and saved: a04-059-s01-01.png
✅ Processed and saved: a04-059-s02-00.png
✅ Processed and saved: a04-059-s00-02.png
✅ Processed and saved: a04-059-s02-01.png
✅ Processed and saved: a04-059-s02-02.png
✅ Processed and saved: a04-059-s02-03.png
✅ Processed and saved: a04-059-s02-04.png
✅ Processed and saved: a04-035-s00-01.png
✅ Processed and saved: a04-035-s00-02.png
✅ Processed and saved: a04-035-s01-00.png
✅ Processed and saved: a04-035-s01-01.png
✅ Processed and saved: a04-035-s01-02.png
✅ Processed and saved: a04-035-s01-03.png
✅ Processed and saved: a04-035-s01-04.png
✅ Processed and saved: a04-035-s01-05.png
✅ Processed and saved: a04-035-s02-00.png
✅ Processed and saved: a04-035-s02-01.png
✅ Processed and saved: a04-035-s02-02.png
✅ Processed and saved: a04-035-s00-00.png
✅ Processed and saved: a04-043-s02-00.png
✅ Processed and saved: a04-043-s02-01.png
✅ Processed and saved: a04-043-s00-00.png
✅ Processed and saved: a04-043-s00-01.png
✅ Processed and saved: a04-043-s01-02.png
✅ Processed and saved: a04-043-s01-01.png
✅ Processed and saved: a04-043-s01-00.png
✅ Processed and saved: a04-043-s02-02.png
✅ Processed and saved: a04-043-s02-03.png
✅ Processed and saved: a04-043-s02-04.png
✅ Processed and saved: a04-043-s01-03.png
✅ Processed and saved: a04-050-s00-01.png
✅ Processed and saved: a04-050-s00-00.png
✅ Processed and saved: a04-050-s01-00.png
✅ Processed and saved: a04-050-s01-01.png
✅ Processed and saved: a04-050-s02-01.png
✅ Processed and saved: a04-050-s02-00.png
✅ Processed and saved: a04-050-s01-02.png
✅ Processed and saved: a04-050-s00-02.png
✅ Processed and saved: a04-050-s02-02.png
✅ Processed and saved: a04-072-s00-01.png
✅ Processed and saved: a04-072-s00-02.png
✅ Processed and saved: a04-072-s00-03.png
✅ Processed and saved: a04-072-s01-03.png
✅ Processed and saved: a04-072-s01-00.png
✅ Processed and saved: a04-072-s00-00.png
✅ Processed and saved: a04-072-s01-01.png
✅ Processed and saved: a04-072-s01-02.png
✅ Processed and saved: a04-072-s02-00.png
✅ Processed and saved: a04-072-s03-01.png
✅ Processed and saved: a04-072-s03-02.png
✅ Processed and saved: a04-072-s02-01.png
✅ Processed and saved: a04-072-s03-00.png
✅ Processed and saved: a04-031-s00-00.png
✅ Processed and saved: a04-031-s00-01.png
✅ Processed and saved: a04-031-s01-00.png
✅ Processed and saved: a04-031-s00-02.png
✅ Processed and saved: a04-031-s01-01.png
✅ Processed and saved: a04-031-s00-03.png
✅ Processed and saved: a04-031-s01-04.png
✅ Processed and saved: a04-031-s02-01.png
✅ Processed and saved: a04-031-s01-02.png
✅ Processed and saved: a04-031-s01-03.png
✅ Processed and saved: a04-031-s02-00.png
✅ Processed and saved: a04-031-s02-02.png
✅ Processed and saved: a04-085-s00-00.png
✅ Processed and saved: a04-085-s00-01.png
✅ Processed and saved: a04-085-s00-02.png
✅ Processed and saved: a04-085-s00-03.png
✅ Processed and saved: a04-085-s01-01.png
✅ Processed and saved: a04-085-s01-00.png
✅ Processed and saved: a04-085-s01-04.png
✅ Processed and saved: a04-085-s01-02.png
✅ Processed and saved: a04-085-s01-03.png
✅ Processed and saved: a04-085-s02-00.png
✅ Processed and saved: a04-085-s02-01.png
✅ Processed and saved: a04-069-s00-01.png
✅ Processed and saved: a04-069-s00-03.png
✅ Processed and saved: a04-069-s01-01.png
✅ Processed and saved: a04-069-s00-02.png
✅ Processed and saved: a04-069-s00-00.png
✅ Processed and saved: a04-069-s01-00.png
✅ Processed and saved: a04-069-s01-02.png
✅ Processed and saved: a04-069-s01-05.png
✅ Processed and saved: a04-069-s01-03.png
✅ Processed and saved: a04-069-s01-04.png
✅ Processed and saved: a04-023-s00-01.png
✅ Processed and saved: a04-023-s01-00.png
✅ Processed and saved: a04-023-s00-03.png
✅ Processed and saved: a04-023-s00-02.png
✅ Processed and saved: a04-023-s00-00.png
✅ Processed and saved: a04-023-s01-01.png
✅ Processed and saved: a04-023-s02-00.png
✅ Processed and saved: a04-023-s01-02.png
✅ Processed and saved: a04-023-s02-01.png
✅ Processed and saved: a04-054-s01-00.png
✅ Processed and saved: a04-054-s01-01.png
✅ Processed and saved: a04-054-s03-00.png
✅ Processed and saved: a04-054-s02-00.png
✅ Processed and saved: a04-054-s02-02.png
✅ Processed and saved: a04-054-s00-00.png
✅ Processed and saved: a04-054-s03-01.png
✅ Processed and saved: a04-054-s02-01.png
✅ Processed and saved: a04-000-s00-01.png
✅ Processed and saved: a04-000-s01-00.png
✅ Processed and saved: a04-000-s00-03.png
✅ Processed and saved: a04-000-s00-00.png
✅ Processed and saved: a04-000-s00-02.png
✅ Processed and saved: a04-000-s01-01.png
✅ Processed and saved: a04-000-s01-02.png
✅ Processed and saved: a04-000-s01-03.png
✅ Processed and saved: a04-015-s00-01.png
✅ Processed and saved: a04-015-s00-02.png
✅ Processed and saved: a04-015-s01-00.png
✅ Processed and saved: a04-015-s01-01.png
✅ Processed and saved: a04-015-s00-00.png
✅ Processed and saved: a04-015-s02-02.png
✅ Processed and saved: a04-015-s02-00.png
✅ Processed and saved: a04-015-s01-03.png
✅ Processed and saved: a04-015-s02-01.png
✅ Processed and saved: a04-015-s01-02.png
✅ Processed and saved: a04-096-s00-01.png
✅ Processed and saved: a04-096-s00-02.png
✅ Processed and saved: a04-096-s00-03.png
✅ Processed and saved: a04-096-s01-00.png
✅ Processed and saved: a04-096-s01-01.png
✅ Processed and saved: a04-096-s01-02.png
✅ Processed and saved: a04-096-s01-04.png
✅ Processed and saved: a04-096-s00-04.png
✅ Processed and saved: a04-096-s00-00.png
✅ Processed and saved: a04-096-s00-05.png
✅ Processed and saved: a04-096-s01-03.png
✅ Processed and saved: a04-103-s00-01.png
✅ Processed and saved: a04-103-s00-00.png
✅ Processed and saved: a04-103-s00-02.png
✅ Processed and saved: a04-103-s00-03.png
✅ Processed and saved: a04-103-s01-00.png
✅ Processed and saved: a04-103-s01-02.png
✅ Processed and saved: a04-103-s01-01.png
✅ Processed and saved: a04-103-s01-03.png
✅ Processed and saved: a04-103-s01-04.png
✅ Processed and saved: a04-103-s01-05.png
✅ Processed and saved: a04-047-s01-03.png
✅ Processed and saved: a04-047-s00-00.png
✅ Processed and saved: a04-047-s01-01.png
✅ Processed and saved: a04-047-s00-03.png
✅ Processed and saved: a04-047-s01-00.png
✅ Processed and saved: a04-047-s00-02.png
✅ Processed and saved: a04-047-s01-02.png
✅ Processed and saved: a04-047-s00-01.png
✅ Processed and saved: a04-047-s01-05.png
✅ Processed and saved: a04-047-s01-04.png
✅ Processed and saved: a04-039-s00-00.png
✅ Processed and saved: a04-039-s00-01.png
✅ Processed and saved: a04-039-s01-02.png
✅ Processed and saved: a04-039-s02-00.png
✅ Processed and saved: a04-039-s02-01.png
✅ Processed and saved: a04-039-s00-03.png
✅ Processed and saved: a04-039-s00-02.png
✅ Processed and saved: a04-039-s01-01.png
✅ Processed and saved: a04-039-s01-00.png
✅ Processed and saved: a04-039-s02-02.png
✅ Processed and saved: a04-006-s01-02.png
✅ Processed and saved: a04-006-s01-03.png
✅ Processed and saved: a04-006-s00-02.png
✅ Processed and saved: a04-006-s00-01.png
✅ Processed and saved: a04-006-s00-00.png
✅ Processed and saved: a04-006-s01-01.png
✅ Processed and saved: a04-006-s01-00.png
✅ Processed and saved: a04-006-s02-00.png
✅ Processed and saved: a04-006-s02-02.png
✅ Processed and saved: a04-006-s02-03.png
✅ Processed and saved: a04-006-s02-01.png
✅ Processed and saved: a04-006-s02-04.png
✅ Processed and saved: a04-099-s00-00.png
✅ Processed and saved: a04-099-s00-03.png
✅ Processed and saved: a04-099-s02-01.png
✅ Processed and saved: a04-099-s02-00.png
✅ Processed and saved: a04-099-s01-00.png
✅ Processed and saved: a04-099-s02-02.png
✅ Processed and saved: a04-099-s00-01.png
✅ Processed and saved: a04-099-s01-01.png
✅ Processed and saved: a04-099-s00-02.png
✅ Processed and saved: a04-099-s02-04.png
✅ Processed and saved: a04-099-s02-03.png
✅ Processed and saved: a04-099-s02-05.png
✅ Processed and saved: a04-099-s02-06.png
✅ Processed and saved: k03-180-s02-00.png
✅ Processed and saved: k03-180-s01-00.png
✅ Processed and saved: k03-180-s02-01.png
✅ Processed and saved: k03-180-s00-00.png
✅ Processed and saved: k03-180-s05-00.png
✅ Processed and saved: k03-180-s03-00.png
✅ Processed and saved: k03-180-s04-00.png
✅ Processed and saved: k03-180-s05-01.png
✅ Processed and saved: k03-180-s04-01.png
✅ Processed and saved: k03-180-s06-01.png
✅ Processed and saved: k03-180-s06-00.png
✅ Processed and saved: k03-144-s01-00.png
✅ Processed and saved: k03-144-s00-00.png
✅ Processed and saved: k03-144-s00-01.png
✅ Processed and saved: k03-144-s02-00.png
✅ Processed and saved: k03-144-s02-01.png
✅ Processed and saved: k03-144-s03-00.png
✅ Processed and saved: k03-144-s05-00.png
✅ Processed and saved: k03-144-s04-00.png
✅ Processed and saved: k03-144-s03-01.png
✅ Processed and saved: k03-144-s07-00.png
✅ Processed and saved: k03-144-s06-01.png
✅ Processed and saved: k03-144-s06-02.png
✅ Processed and saved: k03-144-s07-01.png
✅ Processed and saved: k03-144-s06-00.png
✅ Processed and saved: k03-144-s08-00.png
✅ Processed and saved: k03-117-s00-01.png
✅ Processed and saved: k03-117-s01-00.png
✅ Processed and saved: k03-117-s00-00.png
✅ Processed and saved: k03-117-s00-04.png
✅ Processed and saved: k03-117-s00-02.png
✅ Processed and saved: k03-117-s00-05.png
✅ Processed and saved: k03-117-s01-01.png
✅ Processed and saved: k03-117-s01-02.png
✅ Processed and saved: k03-117-s01-03.png
✅ Processed and saved: k03-117-s00-03.png
✅ Processed and saved: k03-138-s02-00.png
✅ Processed and saved: k03-138-s02-01.png
✅ Processed and saved: k03-138-s04-01.png
✅ Processed and saved: k03-138-s03-01.png
✅ Processed and saved: k03-138-s04-00.png
✅ Processed and saved: k03-138-s01-01.png
✅ Processed and saved: k03-138-s03-00.png
✅ Processed and saved: k03-138-s01-00.png
✅ Processed and saved: k03-138-s00-00.png
✅ Processed and saved: k03-138-s04-02.png
✅ Processed and saved: k03-152-s00-01.png
✅ Processed and saved: k03-152-s02-00.png
✅ Processed and saved: k03-152-s02-01.png
✅ Processed and saved: k03-152-s02-02.png
✅ Processed and saved: k03-152-s00-00.png
✅ Processed and saved: k03-152-s01-00.png
✅ Processed and saved: k03-152-s03-00.png
✅ Processed and saved: k03-152-s01-01.png
✅ Processed and saved: k03-152-s03-01.png
✅ Processed and saved: k03-152-s03-02.png
✅ Processed and saved: k03-157-s00-00.png
✅ Processed and saved: k03-157-s02-00.png
✅ Processed and saved: k03-157-s03-00.png
✅ Processed and saved: k03-157-s03-01.png
✅ Processed and saved: k03-157-s04-00.png
✅ Processed and saved: k03-157-s01-00.png
✅ Processed and saved: k03-157-s04-01.png
✅ Processed and saved: k03-157-s05-00.png
✅ Processed and saved: k03-157-s01-01.png
✅ Processed and saved: k03-157-s05-01.png
✅ Processed and saved: k03-164-s00-00.png
✅ Processed and saved: k03-164-s01-00.png
✅ Processed and saved: k03-164-s04-01.png
✅ Processed and saved: k03-164-s04-02.png
✅ Processed and saved: k03-164-s04-03.png
✅ Processed and saved: k03-164-s02-01.png
✅ Processed and saved: k03-164-s02-00.png
✅ Processed and saved: k03-164-s02-02.png
✅ Processed and saved: k03-164-s03-01.png
✅ Processed and saved: k03-164-s03-00.png
✅ Processed and saved: k03-164-s04-00.png
✅ Processed and saved: k04-126-s04-01.png
✅ Processed and saved: k04-126-s05-00.png
✅ Processed and saved: k04-126-s08-00.png
✅ Processed and saved: k04-126-s08-01.png
✅ Processed and saved: k04-126-s02-00.png
✅ Processed and saved: k04-126-s01-00.png
✅ Processed and saved: k04-126-s00-00.png
✅ Processed and saved: k04-126-s00-01.png
✅ Processed and saved: k04-126-s03-00.png
✅ Processed and saved: k04-126-s04-02.png
✅ Processed and saved: k04-126-s06-00.png
✅ Processed and saved: k04-126-s06-01.png
✅ Processed and saved: k04-126-s04-00.png
✅ Processed and saved: k04-126-s07-00.png
✅ Processed and saved: k04-110-s01-01.png
✅ Processed and saved: k04-110-s02-02.png
✅ Processed and saved: k04-110-s02-00.png
✅ Processed and saved: k04-110-s03-01.png
✅ Processed and saved: k04-110-s02-01.png
✅ Processed and saved: k04-110-s00-02.png
✅ Processed and saved: k04-110-s03-00.png
✅ Processed and saved: k04-110-s00-00.png
✅ Processed and saved: k04-110-s00-01.png
✅ Processed and saved: k04-110-s01-00.png
✅ Processed and saved: k04-110-s02-03.png
✅ Processed and saved: k04-110-s03-02.png
✅ Processed and saved: k04-110-s03-03.png
✅ Processed and saved: k04-110-s03-04.png
✅ Processed and saved: k04-142-s00-00.png
✅ Processed and saved: k04-142-s02-02.png
✅ Processed and saved: k04-142-s01-00.png
✅ Processed and saved: k04-142-s02-00.png
✅ Processed and saved: k04-142-s02-01.png
✅ Processed and saved: k04-142-s01-01.png
✅ Processed and saved: k04-142-s03-00.png
✅ Processed and saved: k04-142-s04-00.png
✅ Processed and saved: k04-142-s05-01.png
✅ Processed and saved: k04-142-s05-00.png
✅ Processed and saved: k04-142-s05-02.png
✅ Processed and saved: k04-119-s01-00.png
✅ Processed and saved: k04-119-s02-01.png
✅ Processed and saved: k04-119-s01-01.png
✅ Processed and saved: k04-119-s02-00.png
✅ Processed and saved: k04-119-s00-00.png
✅ Processed and saved: k04-119-s02-02.png
✅ Processed and saved: k04-119-s04-00.png
✅ Processed and saved: k04-119-s04-01.png
✅ Processed and saved: k04-119-s03-01.png
✅ Processed and saved: k04-119-s03-02.png
✅ Processed and saved: k04-119-s03-00.png
✅ Processed and saved: k04-119-s05-00.png
✅ Processed and saved: k04-085-s00-01.png

## Creating a Dataframe so it could be used to merge

In [2]:

import pandas as pd
sentence_df = pd.read_csv("/content/drive/MyDrive/ComputerVision/VisionSpeak/Sentence_Metadata.csv")

In [3]:
sentence_df

,form_id,image_path,transcription
0,a01-000u-s00-00,/content/drive/MyDrive/ComputerVision/sentence...,A MOVE to stop Mr. Gaitskell from
1,a01-000u-s00-01,/content/drive/MyDrive/ComputerVision/sentence...,nominating any more Labour life Peers
2,a01-000u-s00-02,/content/drive/MyDrive/ComputerVision/sentence...,is to be made at a meeting of Labour
3,a01-000u-s00-03,/content/drive/MyDrive/ComputerVision/sentence...,M Ps tomorrow .
4,a01-000u-s01-00,/content/drive/MyDrive/ComputerVision/sentence...,Mr. Michael Foot has
...,...,...,...
16747,r06-143-s01-01,/content/drive/MyDrive/ComputerVision/sentence...,"in front of her , but she said :"
16748,r06-143-s02-00,/content/drive/MyDrive/ComputerVision/sentence...,' Philip 's awfully lucky .
16749,r06-143-s03-00,/content/drive/MyDrive/ComputerVision/sentence...,I wish I went to that school .
16750,r06-143-s04-00,/content/drive/MyDrive/ComputerVision/sentence...,Did you notice
16751,r06-143-s04-01,/content/drive/MyDrive/ComputerVision/sentence...,that girl who said hullo to him in the garden ?

## Reading images with the ground truth

### Pre- processing the ImHANDWRTITNG dataset 1 : metadata creation

In [13]:

import os
import csv
import concurrent.futures
from collections import defaultdict

# Paths
base_folder = "/content/drive/MyDrive/ComputerVision/"  # This should contain formsA-D, formsE-H, ...
lines_txt_path = "/content/drive/MyDrive/ComputerVision/ascii/lines.txt"  # Adjust if needed
output_csv = "/content/drive/MyDrive/ComputerVision/VisionSpeak/Handwriting_1_matadata.csv"

# Step 1: Load and parse lines.txt
form_lines = defaultdict(list)

with open(lines_txt_path, "r", encoding="utf-8") as f:
    for line in f:
        if line.startswith("#") or not line.strip():
            continue
        parts = line.strip().split()
        line_id = parts[0]
        form_id = "-".join(line_id.split("-")[:2])
        text = " ".join(parts[8:]).replace("|", " ")
        form_lines[form_id].append(text)

# Step 2: Scan all folders for image paths
def scan_for_images(folder):
    img_paths = {}
    for root, _, files in os.walk(folder):
        for file in files:
            if file.endswith((".png", ".jpeg", ".jpg")):
                form_id = os.path.splitext(file)[0]
                img_paths[form_id] = os.path.join(root, file)
    return img_paths

# Use multithreading for scanning
form_image_paths = {}

with concurrent.futures.ThreadPoolExecutor() as executor:
    futures = [executor.submit(scan_for_images, os.path.join(base_folder, subfolder))
               for subfolder in os.listdir(base_folder)
               if subfolder.startswith("forms")]
    for future in concurrent.futures.as_completed(futures):
        form_image_paths.update(future.result())

# Step 3: Build dataset
dataset = []

for form_id, lines in form_lines.items():
    if form_id in form_image_paths:
        image_path = form_image_paths[form_id]
        text = " ".join(lines)
        dataset.append([form_id, image_path, text])

# Step 4: Write to CSV
with open(output_csv, "w", newline="", encoding="utf-8") as out_file:
    writer = csv.writer(out_file)
    writer.writerow(["form_id", "image_path", "transcription"])
    writer.writerows(dataset)

print(f"Dataset saved to: {output_csv}")

Dataset saved to: /content/drive/MyDrive/ComputerVision/VisionSpeak/Handwriting_1_matadata.csv

## Preprocessing image: the full handwritten

In [14]:

preprocess_folder(
    input_folder="/content/drive/MyDrive/ComputerVision/formsA-D",
    output_folder="/content/drive/MyDrive/ComputerVision/formsA-D",
    binarize=True,
    use_bilateral=True
)

✅ Processed and saved: a01-000u.png
✅ Processed and saved: a01-003u.png
✅ Processed and saved: a01-000x.png
✅ Processed and saved: a01-011.png
✅ Processed and saved: a01-007u.png
✅ Processed and saved: a01-003x.png
✅ Processed and saved: a01-003.png
✅ Processed and saved: a01-011u.png
✅ Processed and saved: a01-011x.png
✅ Processed and saved: a01-014.png
✅ Processed and saved: a01-007x.png
✅ Processed and saved: a01-007.png
✅ Processed and saved: a01-014u.png
✅ Processed and saved: a01-014x.png
✅ Processed and saved: a01-020.png
✅ Processed and saved: a01-026.png
✅ Processed and saved: a01-020u.png
✅ Processed and saved: a01-020x.png
✅ Processed and saved: a01-026x.png
✅ Processed and saved: a01-030u.png
✅ Processed and saved: a01-026u.png
✅ Processed and saved: a01-030.png
✅ Processed and saved: a01-038x.png
✅ Processed and saved: a01-030x.png
✅ Processed and saved: a01-043.png
✅ Processed and saved: a01-038.png
✅ Processed and saved: a01-043u.png
✅ Processed and saved: a01-049.png
✅ Processed and saved: a01-049u.png
✅ Processed and saved: a01-049x.png
✅ Processed and saved: a01-043x.png
✅ Processed and saved: a01-053.png
✅ Processed and saved: a01-053u.png
✅ Processed and saved: a01-058.png
✅ Processed and saved: a01-053x.png
✅ Processed and saved: a01-058u.png
✅ Processed and saved: a01-063u.png
✅ Processed and saved: a01-063.png
✅ Processed and saved: a01-063x.png
✅ Processed and saved: a01-068u.png
✅ Processed and saved: a01-077.png
✅ Processed and saved: a01-058x.png
✅ Processed and saved: a01-072u.png
✅ Processed and saved: a01-072x.png
✅ Processed and saved: a01-082u.png
✅ Processed and saved: a01-077u.png
✅ Processed and saved: a01-087.png
✅ Processed and saved: a01-091.png
✅ Processed and saved: a01-087u.png
✅ Processed and saved: a01-096u.png
✅ Processed and saved: a01-102u.png
✅ Processed and saved: a01-091u.png
✅ Processed and saved: a01-107.png
✅ Processed and saved: a01-107u.png
✅ Processed and saved: a01-102.png
✅ Processed and saved: a01-117.png
✅ Processed and saved: a01-113u.png
✅ Processed and saved: a01-117u.png
✅ Processed and saved: a01-113.png
✅ Processed and saved: a01-122.png
✅ Processed and saved: a01-128.png
✅ Processed and saved: a01-122u.png
✅ Processed and saved: a01-128u.png
✅ Processed and saved: a01-132x.png
✅ Processed and saved: a01-132.png
✅ Processed and saved: a01-132u.png
✅ Processed and saved: a02-004.png
✅ Processed and saved: a02-000.png
✅ Processed and saved: a02-008.png
✅ Processed and saved: a02-012.png
✅ Processed and saved: a02-017.png
✅ Processed and saved: a02-020.png
✅ Processed and saved: a02-032.png
✅ Processed and saved: a02-024.png
✅ Processed and saved: a02-027.png
✅ Processed and saved: a02-042.png
✅ Processed and saved: a02-037.png
✅ Processed and saved: a02-050.png
✅ Processed and saved: a02-046.png
✅ Processed and saved: a02-053.png
✅ Processed and saved: a02-062.png
✅ Processed and saved: a02-067.png
✅ Processed and saved: a02-057.png
✅ Processed and saved: a02-078.png
✅ Processed and saved: a02-072.png
✅ Processed and saved: a02-082.png
✅ Processed and saved: a02-086.png
✅ Processed and saved: a02-093.png
✅ Processed and saved: a02-090.png
✅ Processed and saved: a02-098.png
✅ Processed and saved: a02-102.png
✅ Processed and saved: a02-106.png
✅ Processed and saved: a02-111.png
✅ Processed and saved: a02-116.png
✅ Processed and saved: a02-124.png
✅ Processed and saved: a02-120.png
✅ Processed and saved: a03-006.png
✅ Processed and saved: a03-009.png
✅ Processed and saved: a03-011.png
✅ Processed and saved: a03-023.png
✅ Processed and saved: a03-020.png
✅ Processed and saved: a03-014.png
✅ Processed and saved: a03-017.png
✅ Processed and saved: a03-027.png
✅ Processed and saved: a03-037.png
✅ Processed and saved: a03-030.png
✅ Processed and saved: a03-034.png
✅ Processed and saved: a03-040.png
✅ Processed and saved: a03-043.png
✅ Processed and saved: a03-050.png
✅ Processed and saved: a03-047.png
✅ Processed and saved: a03-054.png
✅ Processed and saved: a03-066.png
✅ Processed and saved: a03-059.png
✅ Processed and saved: a03-063.png
✅ Processed and saved: a03-073.png
✅ Processed and saved: a03-089.png
✅ Processed and saved: a03-071.png
✅ Processed and saved: a03-080.png
✅ Processed and saved: a04-003.png
✅ Processed and saved: a04-006.png
✅ Processed and saved: a04-000.png
✅ Processed and saved: a04-010.png
✅ Processed and saved: a04-015.png
✅ Processed and saved: a04-019.png
✅ Processed and saved: a04-023.png
✅ Processed and saved: a04-027.png
✅ Processed and saved: a04-031.png
✅ Processed and saved: a04-035.png
✅ Processed and saved: a04-039.png
✅ Processed and saved: a04-043.png
✅ Processed and saved: a04-054.png
✅ Processed and saved: a04-047.png
✅ Processed and saved: a04-050.png
✅ Processed and saved: a04-059.png
✅ Processed and saved: a04-066.png
✅ Processed and saved: a04-072.png
✅ Processed and saved: a04-069.png
✅ Processed and saved: a04-081.png
✅ Processed and saved: a04-085.png
✅ Processed and saved: a04-092.png
✅ Processed and saved: a04-099.png
✅ Processed and saved: a04-089.png
✅ Processed and saved: a04-103.png
✅ Processed and saved: a04-096.png
✅ Processed and saved: a05-004.png
✅ Processed and saved: a05-009.png
✅ Processed and saved: a05-000.png
✅ Processed and saved: a05-013.png
✅ Processed and saved: a05-022.png
✅ Processed and saved: a05-025.png
✅ Processed and saved: a05-017.png
✅ Processed and saved: a05-039.png
✅ Processed and saved: a05-029.png
✅ Processed and saved: a05-044.png
✅ Processed and saved: a05-048.png
✅ Processed and saved: a05-053.png
✅ Processed and saved: a05-062.png
✅ Processed and saved: a05-069.png
✅ Processed and saved: a05-058.png
✅ Processed and saved: a05-080.png
✅ Processed and saved: a05-073.png
✅ Processed and saved: a05-089.png
✅ Processed and saved: a05-094.png
✅ Processed and saved: a05-084.png
✅ Processed and saved: a05-113.png
✅ Processed and saved: a05-099.png
✅ Processed and saved: a05-104.png
✅ Processed and saved: a05-108.png
✅ Processed and saved: a05-121.png
✅ Processed and saved: a05-116.png
✅ Processed and saved: a05-125.png
✅ Processed and saved: a06-008.png
✅ Processed and saved: a06-004.png
✅ Processed and saved: a06-000.png
✅ Processed and saved: a06-020.png
✅ Processed and saved: a06-014.png
✅ Processed and saved: a06-025.png
✅ Processed and saved: a06-036.png
✅ Processed and saved: a06-051.png
✅ Processed and saved: a06-039.png
✅ Processed and saved: a06-064.png
✅ Processed and saved: a06-070.png
✅ Processed and saved: a06-044.png
✅ Processed and saved: a06-057.png
✅ Processed and saved: a06-090.png
✅ Processed and saved: a06-100.png
✅ Processed and saved: a06-075.png
✅ Processed and saved: a06-095.png
✅ Processed and saved: a06-110.png
✅ Processed and saved: a06-119.png
✅ Processed and saved: a06-124.png
✅ Processed and saved: a06-114.png
✅ Processed and saved: a06-128.png
✅ Processed and saved: a06-134.png
✅ Processed and saved: a06-141.png
✅ Processed and saved: a06-147.png
✅ Processed and saved: a06-152.png
✅ Processed and saved: a06-157.png
✅ Processed and saved: b01-000.png
✅ Processed and saved: b01-004.png
✅ Processed and saved: b01-009.png
✅ Processed and saved: b01-018.png
✅ Processed and saved: b01-023.png
✅ Processed and saved: b01-014.png
✅ Processed and saved: b01-027.png
✅ Processed and saved: b01-038.png
✅ Processed and saved: b01-033.png
✅ Processed and saved: b01-044.png
✅ Processed and saved: b01-053.png
✅ Processed and saved: b01-049.png
✅ Processed and saved: b01-062.png
✅ Processed and saved: b01-057.png
✅ Processed and saved: b01-079.png
✅ Processed and saved: b01-073.png
✅ Processed and saved: b01-084.png
✅ Processed and saved: b01-094.png
✅ Processed and saved: b01-089.png
✅ Processed and saved: b01-118.png
✅ Processed and saved: b01-113.png
✅ Processed and saved: b01-127.png
✅ Processed and saved: b01-122.png
✅ Processed and saved: b01-136.png
✅ Processed and saved: b01-132.png
✅ Processed and saved: b02-097.png
✅ Processed and saved: b02-013.png
✅ Processed and saved: b02-045.png
✅ Processed and saved: b02-035.png
✅ Processed and saved: b03-025.png
✅ Processed and saved: b02-102.png
✅ Processed and saved: b02-105.png
✅ Processed and saved: b03-087.png
✅ Processed and saved: b03-092.png
✅ Processed and saved: b03-098.png
✅ Processed and saved: b03-109.png
✅ Processed and saved: b03-114.png
✅ Processed and saved: b04-004.png
✅ Processed and saved: b03-104.png
✅ Processed and saved: b04-000.png
✅ Processed and saved: b04-010.png
✅ Processed and saved: b04-026.png
✅ Processed and saved: b04-020.png
✅ Processed and saved: b04-034.png
✅ Processed and saved: b04-040.png
✅ Processed and saved: b04-047.png
✅ Processed and saved: b04-060.png
✅ Processed and saved: b04-054.png
✅ Processed and saved: b04-075.png
✅ Processed and saved: b04-081.png
✅ Processed and saved: b04-066.png
✅ Processed and saved: b04-089.png
✅ Processed and saved: b04-096.png
✅ Processed and saved: b04-107.png
✅ Processed and saved: b04-103.png
✅ Processed and saved: b04-116.png
✅ Processed and saved: b04-121.png
✅ Processed and saved: b04-134.png
✅ Processed and saved: b04-128.png
✅ Processed and saved: b04-154.png
✅ Processed and saved: b04-140.png
✅ Processed and saved: b04-147.png
✅ Processed and saved: b04-169.png
✅ Processed and saved: b04-162.png
✅ Processed and saved: b04-175.png
✅ Processed and saved: b04-181.png
✅ Processed and saved: b04-187.png
✅ Processed and saved: b04-195.png
✅ Processed and saved: b05-017.png
✅ Processed and saved: b04-202.png
✅ Processed and saved: b04-208.png
✅ Processed and saved: b05-032.png
✅ Processed and saved: b05-038.png
✅ Processed and saved: b05-042.png
✅ Processed and saved: b05-055.png
✅ Processed and saved: b05-050.png
✅ Processed and saved: b05-058.png
✅ Processed and saved: b05-045.png
✅ Processed and saved: b05-067.png
✅ Processed and saved: b05-071.png
✅ Processed and saved: b05-062.png
✅ Processed and saved: b05-079.png
✅ Processed and saved: b05-074.png
✅ Processed and saved: b05-083.png
✅ Processed and saved: b05-098.png
✅ Processed and saved: b06-008.png
✅ Processed and saved: b06-000.png
✅ Processed and saved: b06-015.png
✅ Processed and saved: b06-004.png
✅ Processed and saved: b06-012.png
✅ Processed and saved: b05-088.png
✅ Processed and saved: b06-019.png
✅ Processed and saved: b06-023.png
✅ Processed and saved: b06-027.png
✅ Processed and saved: b06-032.png
✅ Processed and saved: b06-036.png
✅ Processed and saved: b06-045.png
✅ Processed and saved: b06-042.png
✅ Processed and saved: b06-049.png
✅ Processed and saved: b06-056.png
✅ Processed and saved: b06-059.png
✅ Processed and saved: b06-053.png
✅ Processed and saved: b06-064.png
✅ Processed and saved: b06-071.png
✅ Processed and saved: b06-068.png
✅ Processed and saved: b06-075.png
✅ Processed and saved: b06-079.png
✅ Processed and saved: b06-090.png
✅ Processed and saved: b06-082.png
✅ Processed and saved: b06-087.png
✅ Processed and saved: b06-097.png
✅ Processed and saved: b06-093.png
✅ Processed and saved: b06-100.png
✅ Processed and saved: c01-009.png
✅ Processed and saved: b06-110.png
✅ Processed and saved: c01-014.png
✅ Processed and saved: c02-000.png
✅ Processed and saved: c01-066.png
✅ Processed and saved: c02-003.png
✅ Processed and saved: c02-007.png
✅ Processed and saved: c02-017.png
✅ Processed and saved: c02-012.png
✅ Processed and saved: c02-022.png
✅ Processed and saved: c02-026.png
✅ Processed and saved: c02-035.png
✅ Processed and saved: c02-030.png
✅ Processed and saved: c02-056.png
✅ Processed and saved: c02-049.png
✅ Processed and saved: c02-078.png
✅ Processed and saved: c02-059.png
✅ Processed and saved: c02-082.png
✅ Processed and saved: c02-089.png
✅ Processed and saved: c03-000a.png
✅ Processed and saved: c03-000c.png
✅ Processed and saved: c03-000b.png
✅ Processed and saved: c03-000e.png
✅ Processed and saved: c03-000f.png
✅ Processed and saved: c03-003a.png
✅ Processed and saved: c03-007.png
✅ Processed and saved: c03-003b.png
✅ Processed and saved: c03-000d.png
✅ Processed and saved: c03-003d.png
✅ Processed and saved: c03-003c.png
✅ Processed and saved: c03-003e.png
✅ Processed and saved: c03-007a.png
✅ Processed and saved: c03-003f.png
✅ Processed and saved: c03-007d.png
✅ Processed and saved: c03-007c.png
✅ Processed and saved: c03-007b.png
✅ Processed and saved: c03-007e.png
✅ Processed and saved: c03-007f.png
✅ Processed and saved: c03-016a.png
✅ Processed and saved: c03-016b.png
✅ Processed and saved: c03-016c.png
✅ Processed and saved: c03-016d.png
✅ Processed and saved: c03-016e.png
✅ Processed and saved: c03-021a.png
✅ Processed and saved: c03-021c.png
✅ Processed and saved: c03-021b.png
✅ Processed and saved: c03-021e.png
✅ Processed and saved: c03-021d.png
✅ Processed and saved: c03-021f.png
✅ Processed and saved: c03-081a.png
✅ Processed and saved: c03-081b.png
✅ Processed and saved: c03-081c.png
✅ Processed and saved: c03-081f.png
✅ Processed and saved: c03-081d.png
✅ Processed and saved: c03-081e.png
✅ Processed and saved: c03-084a.png
✅ Processed and saved: c03-084d.png
✅ Processed and saved: c03-084b.png
✅ Processed and saved: c03-084c.png
✅ Processed and saved: c03-084f.png
✅ Processed and saved: c03-084e.png
✅ Processed and saved: c03-087a.png
✅ Processed and saved: c03-087c.png
✅ Processed and saved: c03-087b.png
✅ Processed and saved: c03-087e.png
✅ Processed and saved: c03-087d.png
✅ Processed and saved: c03-094a.png
✅ Processed and saved: c03-087f.png
✅ Processed and saved: c03-094c.png
✅ Processed and saved: c03-094d.png
✅ Processed and saved: c03-094b.png
✅ Processed and saved: c03-094f.png
✅ Processed and saved: c03-094e.png
✅ Processed and saved: c03-096b.png
✅ Processed and saved: c03-096a.png
✅ Processed and saved: c03-096f.png
✅ Processed and saved: c03-096c.png
✅ Processed and saved: c03-096d.png
✅ Processed and saved: c03-096e.png
✅ Processed and saved: c04-000.png
✅ Processed and saved: c04-004.png
✅ Processed and saved: c04-013.png
✅ Processed and saved: c04-023.png
✅ Processed and saved: c04-008.png
✅ Processed and saved: c04-017.png
✅ Processed and saved: c04-028.png
✅ Processed and saved: c04-039.png
✅ Processed and saved: c04-035.png
✅ Processed and saved: c04-050.png
✅ Processed and saved: c04-044.png
✅ Processed and saved: c04-056.png
✅ Processed and saved: c04-061.png
✅ Processed and saved: c04-066.png
✅ Processed and saved: c04-080.png
✅ Processed and saved: c04-098.png
✅ Processed and saved: c04-089.png
✅ Processed and saved: c04-075.png
✅ Processed and saved: c04-105.png
✅ Processed and saved: c04-110.png
✅ Processed and saved: c04-128.png
✅ Processed and saved: c04-122.png
✅ Processed and saved: c04-116.png
✅ Processed and saved: c04-134.png
✅ Processed and saved: c04-139.png
✅ Processed and saved: c04-144.png
✅ Processed and saved: c04-150.png
✅ Processed and saved: c04-160.png
✅ Processed and saved: c04-156.png
✅ Processed and saved: c04-165.png
✅ Processed and saved: c06-000.png
✅ Processed and saved: c04-170.png
✅ Processed and saved: c06-011.png
✅ Processed and saved: c06-005.png
✅ Processed and saved: c06-014.png
✅ Processed and saved: c06-020.png
✅ Processed and saved: c06-027.png
✅ Processed and saved: c06-039.png
✅ Processed and saved: c06-031.png
✅ Processed and saved: c06-043.png
✅ Processed and saved: c06-052.png
✅ Processed and saved: c06-058.png
✅ Processed and saved: c06-047.png
✅ Processed and saved: c06-076.png
✅ Processed and saved: c06-080.png
✅ Processed and saved: c06-083.png
✅ Processed and saved: c06-087.png
✅ Processed and saved: c06-091.png
✅ Processed and saved: c06-100.png
✅ Processed and saved: c06-095.png
✅ Processed and saved: c06-111.png
✅ Processed and saved: c06-106.png
✅ Processed and saved: c06-103.png
✅ Processed and saved: c06-116.png
✅ Processed and saved: c06-128.png
✅ Processed and saved: c06-138.png
✅ Processed and saved: d01-016.png
✅ Processed and saved: d01-024.png
✅ Processed and saved: d01-052.png
✅ Processed and saved: d01-049.png
✅ Processed and saved: d01-019.png
✅ Processed and saved: d01-080.png
✅ Processed and saved: d01-056.png
✅ Processed and saved: d01-060.png
✅ Processed and saved: d01-098.png
✅ Processed and saved: d01-085.png
✅ Processed and saved: d01-104.png
✅ Processed and saved: d01-123.png
✅ Processed and saved: d01-118.png
✅ Processed and saved: d03-112.png
✅ Processed and saved: d04-005.png
✅ Processed and saved: d04-008.png
✅ Processed and saved: d03-117.png
✅ Processed and saved: d04-012.png
✅ Processed and saved: d04-021.png
✅ Processed and saved: d04-028.png
✅ Processed and saved: d04-016.png
✅ Processed and saved: d04-037.png
✅ Processed and saved: d04-032.png
✅ Processed and saved: d04-047.png
✅ Processed and saved: d04-050.png
✅ Processed and saved: d04-053.png
✅ Processed and saved: d04-058.png
✅ Processed and saved: d04-066.png
✅ Processed and saved: d04-075.png
✅ Processed and saved: d04-081.png
✅ Processed and saved: d04-071.png
✅ Processed and saved: d04-086.png
✅ Processed and saved: d04-101.png
✅ Processed and saved: d04-096.png
✅ Processed and saved: d04-089.png
✅ Processed and saved: d04-117.png
✅ Processed and saved: d04-111.png
✅ Processed and saved: d04-121.png
✅ Processed and saved: d04-125.png
✅ Processed and saved: d05-008.png
✅ Processed and saved: d04-131.png
✅ Processed and saved: d05-025.png
✅ Processed and saved: d05-013.png
✅ Processed and saved: d05-030.png
✅ Processed and saved: d05-021.png
✅ Processed and saved: d05-040.png
✅ Processed and saved: d06-000.png
✅ Processed and saved: d06-003.png
✅ Processed and saved: d06-008.png
✅ Processed and saved: d06-011.png
✅ Processed and saved: d06-015.png
✅ Processed and saved: d06-020.png
✅ Processed and saved: d06-027.png
✅ Processed and saved: d06-025.png
✅ Processed and saved: d06-037.png
✅ Processed and saved: d06-030.png
✅ Processed and saved: d06-050.png
✅ Processed and saved: d06-041.png
✅ Processed and saved: d06-046.png
✅ Processed and saved: d06-056.png
✅ Processed and saved: d06-067.png
✅ Processed and saved: d06-063.png
✅ Processed and saved: d06-076.png
✅ Processed and saved: d06-060.png
✅ Processed and saved: d06-072.png
✅ Processed and saved: d06-086.png
✅ Processed and saved: d06-091.png
✅ Processed and saved: d06-082.png
✅ Processed and saved: d06-100.png
✅ Processed and saved: d06-096.png
✅ Processed and saved: d06-104.png
✅ Processed and saved: d06-107.png
✅ Processed and saved: d07-082.png
✅ Processed and saved: d06-111.png
✅ Processed and saved: d06-113.png
✅ Processed and saved: d07-089.png
✅ Processed and saved: d07-085.png
✅ Processed and saved: d07-093.png
✅ Processed and saved: d07-096.png
✅ Processed and saved: d07-102.png
✅ Processed and saved: d07-100.png
✅ Processed and saved: d04-062.png

In [15]:

preprocess_folder(
    input_folder="/content/drive/MyDrive/ComputerVision/formsE-H",
    output_folder="/content/drive/MyDrive/ComputerVision/formsE-H",
    binarize=True,
    use_bilateral=True
)

✅ Processed and saved: e01-018.png
✅ Processed and saved: e01-035.png
✅ Processed and saved: e01-032.png
✅ Processed and saved: e01-025.png
✅ Processed and saved: e01-050.png
✅ Processed and saved: e01-022.png
✅ Processed and saved: e01-014.png
✅ Processed and saved: e01-055.png
✅ Processed and saved: e01-029.png
✅ Processed and saved: e01-062.png
✅ Processed and saved: e01-081.png
✅ Processed and saved: e01-086.png
✅ Processed and saved: e01-059.png
✅ Processed and saved: e01-092.png
✅ Processed and saved: e01-102.png
✅ Processed and saved: e01-113.png
✅ Processed and saved: e01-107.png
✅ Processed and saved: e01-119.png
✅ Processed and saved: e02-000.png
✅ Processed and saved: e02-014.png
✅ Processed and saved: e02-021.png
✅ Processed and saved: e02-018.png
✅ Processed and saved: e02-025.png
✅ Processed and saved: e02-074.png
✅ Processed and saved: e02-082.png
✅ Processed and saved: e02-086.png
✅ Processed and saved: e02-091.png
✅ Processed and saved: e02-094.png
✅ Processed and saved: e02-100.png
✅ Processed and saved: e02-117.png
✅ Processed and saved: e04-011.png
✅ Processed and saved: e04-000.png
✅ Processed and saved: e04-004.png
✅ Processed and saved: e04-008.png
✅ Processed and saved: e04-019.png
✅ Processed and saved: e04-015.png
✅ Processed and saved: e04-022.png
✅ Processed and saved: e04-026.png
✅ Processed and saved: e04-030.png
✅ Processed and saved: e04-034.png
✅ Processed and saved: e04-043.png
✅ Processed and saved: e04-052.png
✅ Processed and saved: e04-068.png
✅ Processed and saved: e04-038.png
✅ Processed and saved: e04-058.png
✅ Processed and saved: e04-062.png
✅ Processed and saved: e04-079.png
✅ Processed and saved: e04-083.png
✅ Processed and saved: e04-086.png
✅ Processed and saved: e04-095.png
✅ Processed and saved: e04-091.png
✅ Processed and saved: e04-103.png
✅ Processed and saved: e04-109.png
✅ Processed and saved: e04-114.png
✅ Processed and saved: e04-099.png
✅ Processed and saved: e04-119.png
✅ Processed and saved: e04-124.png
✅ Processed and saved: e04-127.png
✅ Processed and saved: e04-132.png
✅ Processed and saved: e06-000.png
✅ Processed and saved: e06-003.png
✅ Processed and saved: e06-010.png
✅ Processed and saved: e06-006.png
✅ Processed and saved: e06-021.png
✅ Processed and saved: e06-015.png
✅ Processed and saved: e06-026.png
✅ Processed and saved: e06-030.png
✅ Processed and saved: e06-037.png
✅ Processed and saved: e06-033.png
✅ Processed and saved: e06-041.png
✅ Processed and saved: e06-049.png
✅ Processed and saved: e06-070.png
✅ Processed and saved: e06-046.png
✅ Processed and saved: e06-053.png
✅ Processed and saved: e07-003.png
✅ Processed and saved: e07-000.png
✅ Processed and saved: e07-007.png
✅ Processed and saved: e07-012.png
✅ Processed and saved: e07-061.png
✅ Processed and saved: e07-072.png
✅ Processed and saved: e07-066.png
✅ Processed and saved: e07-076.png
✅ Processed and saved: e07-079.png
✅ Processed and saved: e07-083.png
✅ Processed and saved: e07-086.png
✅ Processed and saved: e07-090.png
✅ Processed and saved: e07-094.png
✅ Processed and saved: e07-101.png
✅ Processed and saved: e07-098.png
✅ Processed and saved: e07-105.png
✅ Processed and saved: e07-108.png
✅ Processed and saved: e07-112.png
✅ Processed and saved: f01-058.png
✅ Processed and saved: f01-053.png
✅ Processed and saved: f01-066.png
✅ Processed and saved: f01-070.png
✅ Processed and saved: f01-081.png
✅ Processed and saved: f01-135.png
✅ Processed and saved: f01-075.png
✅ Processed and saved: f01-085.png
✅ Processed and saved: f01-143.png
✅ Processed and saved: f01-139.png
✅ Processed and saved: f02-000.png
✅ Processed and saved: f01-147.png
✅ Processed and saved: f02-003.png
✅ Processed and saved: f02-017.png
✅ Processed and saved: f02-020.png
✅ Processed and saved: f02-030.png
✅ Processed and saved: f02-033.png
✅ Processed and saved: f02-036.png
✅ Processed and saved: f02-038.png
✅ Processed and saved: f02-040.png
✅ Processed and saved: f02-044.png
✅ Processed and saved: f02-076.png
✅ Processed and saved: f03-169.png
✅ Processed and saved: f03-174.png
✅ Processed and saved: f03-182.png
✅ Processed and saved: f03-191.png
✅ Processed and saved: f04-007.png
✅ Processed and saved: f04-004.png
✅ Processed and saved: f04-011.png
✅ Processed and saved: f04-016.png
✅ Processed and saved: f04-020.png
✅ Processed and saved: f04-028.png
✅ Processed and saved: f04-024.png
✅ Processed and saved: f04-032.png
✅ Processed and saved: f04-035.png
✅ Processed and saved: f04-039.png
✅ Processed and saved: f04-043.png
✅ Processed and saved: f04-049.png
✅ Processed and saved: f04-046.png
✅ Processed and saved: f04-057.png
✅ Processed and saved: f04-053.png
✅ Processed and saved: f04-061.png
✅ Processed and saved: f04-064.png
✅ Processed and saved: f04-068.png
✅ Processed and saved: f04-071.png
✅ Processed and saved: f04-074.png
✅ Processed and saved: f04-079.png
✅ Processed and saved: f04-093.png
✅ Processed and saved: f04-083.png
✅ Processed and saved: f04-087.png
✅ Processed and saved: f04-096.png
✅ Processed and saved: f04-100.png
✅ Processed and saved: f07-000.png
✅ Processed and saved: f07-000b.png
✅ Processed and saved: f07-006.png
✅ Processed and saved: f07-002.png
✅ Processed and saved: f07-009.png
✅ Processed and saved: f07-013.png
✅ Processed and saved: f07-016.png
✅ Processed and saved: f07-019b.png
✅ Processed and saved: f07-019a.png
✅ Processed and saved: f07-021a.png
✅ Processed and saved: f07-021b.png
✅ Processed and saved: f07-024b.png
✅ Processed and saved: f07-024a.png
✅ Processed and saved: f07-028a.png
✅ Processed and saved: f07-032a.png
✅ Processed and saved: f07-028b.png
✅ Processed and saved: f07-036.png
✅ Processed and saved: f07-039a.png
✅ Processed and saved: f07-032b.png
✅ Processed and saved: f07-039b.png
✅ Processed and saved: f07-042b.png
✅ Processed and saved: f07-042a.png
✅ Processed and saved: f07-046a.png
✅ Processed and saved: f07-046b.png
✅ Processed and saved: f07-073.png
✅ Processed and saved: f07-076a.png
✅ Processed and saved: f07-069.png
✅ Processed and saved: f07-081a.png
✅ Processed and saved: f07-096.png
✅ Processed and saved: f07-081b.png
✅ Processed and saved: f07-084a.png
✅ Processed and saved: f07-084b.png
✅ Processed and saved: f07-088a.png
✅ Processed and saved: f07-088b.png
✅ Processed and saved: f07-092a.png
✅ Processed and saved: f07-092b.png
✅ Processed and saved: f07-101a.png
✅ Processed and saved: f07-101b.png
✅ Processed and saved: g01-000.png
✅ Processed and saved: g01-004.png
✅ Processed and saved: g01-008.png
✅ Processed and saved: g01-016.png
✅ Processed and saved: g01-012.png
✅ Processed and saved: g01-019.png
✅ Processed and saved: g01-022.png
✅ Processed and saved: g01-025.png
✅ Processed and saved: g01-027.png
✅ Processed and saved: g01-037.png
✅ Processed and saved: g01-031.png
✅ Processed and saved: g01-039.png
✅ Processed and saved: g01-034.png
✅ Processed and saved: g01-067.png
✅ Processed and saved: g01-043.png
✅ Processed and saved: g01-045.png
✅ Processed and saved: g01-070.png
✅ Processed and saved: g01-074.png
✅ Processed and saved: g02-065.png
✅ Processed and saved: g01-083.png
✅ Processed and saved: g01-088.png
✅ Processed and saved: g02-062.png
✅ Processed and saved: g02-059.png
✅ Processed and saved: g03-004.png
✅ Processed and saved: g02-073.png
✅ Processed and saved: g03-000.png
✅ Processed and saved: g03-032.png
✅ Processed and saved: g03-016.png
✅ Processed and saved: g03-040.png
✅ Processed and saved: g03-043.png
✅ Processed and saved: g03-049.png
✅ Processed and saved: g03-058.png
✅ Processed and saved: g03-052.png
✅ Processed and saved: g04-003.png
✅ Processed and saved: g03-064.png
✅ Processed and saved: g04-011.png
✅ Processed and saved: g04-007.png
✅ Processed and saved: g04-014.png
✅ Processed and saved: g04-017.png
✅ Processed and saved: g04-026.png
✅ Processed and saved: g04-032.png
✅ Processed and saved: g04-036.png
✅ Processed and saved: g04-022.png
✅ Processed and saved: g04-043.png
✅ Processed and saved: g04-039.png
✅ Processed and saved: g04-048.png
✅ Processed and saved: g04-055.png
✅ Processed and saved: g04-052.png
✅ Processed and saved: g04-063.png
✅ Processed and saved: g04-060.png
✅ Processed and saved: g04-072.png
✅ Processed and saved: g04-068.png
✅ Processed and saved: g04-081.png
✅ Processed and saved: g04-077.png
✅ Processed and saved: g04-088.png
✅ Processed and saved: g04-092.png
✅ Processed and saved: g04-095.png
✅ Processed and saved: g04-098.png
✅ Processed and saved: g04-101.png
✅ Processed and saved: g04-108.png
✅ Processed and saved: g04-104.png
✅ Processed and saved: g05-087.png
✅ Processed and saved: g05-094.png
✅ Processed and saved: g05-098.png
✅ Processed and saved: g06-011a.png
✅ Processed and saved: g06-011b.png
✅ Processed and saved: g06-011f.png
✅ Processed and saved: g06-011c.png
✅ Processed and saved: g06-011g.png
✅ Processed and saved: g06-011e.png
✅ Processed and saved: g06-011h.png
✅ Processed and saved: g06-011i.png
✅ Processed and saved: g06-011k.png
✅ Processed and saved: g06-011j.png
✅ Processed and saved: g06-011m.png
✅ Processed and saved: g06-011l.png
✅ Processed and saved: g06-011n.png
✅ Processed and saved: g06-011o.png
✅ Processed and saved: g06-011p.png
✅ Processed and saved: g06-018a.png
✅ Processed and saved: g06-011r.png
✅ Processed and saved: g06-018c.png
✅ Processed and saved: g06-018b.png
✅ Processed and saved: g06-018e.png
✅ Processed and saved: g06-018d.png
✅ Processed and saved: g06-018f.png
✅ Processed and saved: g06-018g.png
✅ Processed and saved: g06-018i.png
✅ Processed and saved: g06-018h.png
✅ Processed and saved: g06-018j.png
✅ Processed and saved: g06-018k.png
✅ Processed and saved: g06-018m.png
✅ Processed and saved: g06-018n.png
✅ Processed and saved: g06-018l.png
✅ Processed and saved: g06-018r.png
✅ Processed and saved: g06-018o.png
✅ Processed and saved: g06-026a.png
✅ Processed and saved: g06-018p.png
✅ Processed and saved: g06-026c.png
✅ Processed and saved: g06-026b.png
✅ Processed and saved: g06-026d.png
✅ Processed and saved: g06-026e.png
✅ Processed and saved: g06-026f.png
✅ Processed and saved: g06-026g.png
✅ Processed and saved: g06-026i.png
✅ Processed and saved: g06-026h.png
✅ Processed and saved: g06-026j.png
✅ Processed and saved: g06-026k.png
✅ Processed and saved: g06-026m.png
✅ Processed and saved: g06-026l.png
✅ Processed and saved: g06-026n.png
✅ Processed and saved: g06-026o.png
✅ Processed and saved: g06-026p.png
✅ Processed and saved: g06-026r.png
✅ Processed and saved: g06-031a.png
✅ Processed and saved: g06-031b.png
✅ Processed and saved: g06-031c.png
✅ Processed and saved: g06-031d.png
✅ Processed and saved: g06-031e.png
✅ Processed and saved: g06-031f.png
✅ Processed and saved: g06-031h.png
✅ Processed and saved: g06-031g.png
✅ Processed and saved: g06-031i.png
✅ Processed and saved: g06-031j.png
✅ Processed and saved: g06-031l.png
✅ Processed and saved: g06-031k.png
✅ Processed and saved: g06-031m.png
✅ Processed and saved: g06-031n.png
✅ Processed and saved: g06-031o.png
✅ Processed and saved: g06-031p.png
✅ Processed and saved: g06-037c (1).png
✅ Processed and saved: g06-037b.png
✅ Processed and saved: g06-031r.png
✅ Processed and saved: g06-037c.png
✅ Processed and saved: g06-037d.png
✅ Processed and saved: g06-037e.png
✅ Processed and saved: g06-037f.png
✅ Processed and saved: g06-037h.png
✅ Processed and saved: g06-037g.png
✅ Processed and saved: g06-037i.png
✅ Processed and saved: g06-037j.png
✅ Processed and saved: g06-037k.png
✅ Processed and saved: g06-037l.png
✅ Processed and saved: g06-037n.png
✅ Processed and saved: g06-037m.png
✅ Processed and saved: g06-037o.png
✅ Processed and saved: g06-037p.png
✅ Processed and saved: g06-042b.png
✅ Processed and saved: g06-037r.png
✅ Processed and saved: g06-042a.png
✅ Processed and saved: g06-042d.png
✅ Processed and saved: g06-042c.png
✅ Processed and saved: g06-042e.png
✅ Processed and saved: g06-042f.png
✅ Processed and saved: g06-042h.png
✅ Processed and saved: g06-042g.png
✅ Processed and saved: g06-042i (1).png
✅ Processed and saved: g06-042j.png
✅ Processed and saved: g06-042k.png
✅ Processed and saved: g06-042i.png
✅ Processed and saved: g06-042l.png
✅ Processed and saved: g06-042n.png
✅ Processed and saved: g06-042m.png
✅ Processed and saved: g06-042p.png
✅ Processed and saved: g06-042o.png
✅ Processed and saved: g06-042r.png
✅ Processed and saved: g06-045c.png
✅ Processed and saved: g06-045a.png
✅ Processed and saved: g06-045d.png
✅ Processed and saved: g06-045b.png
✅ Processed and saved: g06-045e.png
✅ Processed and saved: g06-045f.png
✅ Processed and saved: g06-045g.png
✅ Processed and saved: g06-045h.png
✅ Processed and saved: g06-045i.png
✅ Processed and saved: g06-045j.png
✅ Processed and saved: g06-045l.png
✅ Processed and saved: g06-045k.png
✅ Processed and saved: g06-045o.png
✅ Processed and saved: g06-045n.png
✅ Processed and saved: g06-045m.png
✅ Processed and saved: g06-045r.png
✅ Processed and saved: g06-047a.png
✅ Processed and saved: g06-045p.png
✅ Processed and saved: g06-047b.png
✅ Processed and saved: g06-047d.png
✅ Processed and saved: g06-047c.png
✅ Processed and saved: g06-047e.png
✅ Processed and saved: g06-047f.png
✅ Processed and saved: g06-047h.png
✅ Processed and saved: g06-047g.png
✅ Processed and saved: g06-047i.png
✅ Processed and saved: g06-047j.png
✅ Processed and saved: g06-047l.png
✅ Processed and saved: g06-047k.png
✅ Processed and saved: g06-047m.png
✅ Processed and saved: g06-047o.png
✅ Processed and saved: g06-047n.png
✅ Processed and saved: g06-047p.png
✅ Processed and saved: g06-047r.png
✅ Processed and saved: g06-050b.png
✅ Processed and saved: g06-050a.png
✅ Processed and saved: g06-050e.png
✅ Processed and saved: g06-050d.png
✅ Processed and saved: g06-050c.png
✅ Processed and saved: g06-050f.png
✅ Processed and saved: g06-050h.png
✅ Processed and saved: g06-050g.png
✅ Processed and saved: g06-050j.png
✅ Processed and saved: g06-050m.png
✅ Processed and saved: g06-050k.png
✅ Processed and saved: g06-050i.png
✅ Processed and saved: g06-050l.png
✅ Processed and saved: g06-050n.png
✅ Processed and saved: g06-050o.png
✅ Processed and saved: g06-050p.png
✅ Processed and saved: g06-089.png
✅ Processed and saved: g06-050r.png
✅ Processed and saved: g06-093.png
✅ Processed and saved: g06-096.png
✅ Processed and saved: g06-101.png
✅ Processed and saved: g06-105.png
✅ Processed and saved: g06-109.png
✅ Processed and saved: g06-115.png
✅ Processed and saved: g07-000a.png
✅ Processed and saved: g07-003a.png
✅ Processed and saved: g07-003b.png
✅ Processed and saved: g07-000b.png
✅ Processed and saved: g07-007a.png
✅ Processed and saved: g07-007b.png
✅ Processed and saved: g07-010b.png
✅ Processed and saved: g07-014.png
✅ Processed and saved: g07-018a.png
✅ Processed and saved: g07-014b.png
✅ Processed and saved: g07-022a.png
✅ Processed and saved: g07-026a.png
✅ Processed and saved: g07-022b.png
✅ Processed and saved: g07-026b.png
✅ Processed and saved: g07-028a.png
✅ Processed and saved: g07-028b.png
✅ Processed and saved: g07-030.png
✅ Processed and saved: g07-034.png
✅ Processed and saved: g07-038.png
✅ Processed and saved: g07-042.png
✅ Processed and saved: g07-047.png
✅ Processed and saved: g07-044.png
✅ Processed and saved: g07-069a.png
✅ Processed and saved: g07-050.png
✅ Processed and saved: g07-065.png
✅ Processed and saved: g07-074a.png
✅ Processed and saved: g07-079a.png
✅ Processed and saved: g07-071a.png
✅ Processed and saved: g07-077a.png
✅ Processed and saved: h01-000.png
✅ Processed and saved: g07-084.png
✅ Processed and saved: h01-007.png
✅ Processed and saved: h01-004.png
✅ Processed and saved: h01-010.png
✅ Processed and saved: h01-014.png
✅ Processed and saved: h01-024.png
✅ Processed and saved: h01-018.png
✅ Processed and saved: h01-027.png
✅ Processed and saved: h01-030.png
✅ Processed and saved: h02-008.png
✅ Processed and saved: h02-004.png
✅ Processed and saved: h02-012.png
✅ Processed and saved: h02-019.png
✅ Processed and saved: h02-017.png
✅ Processed and saved: h02-022.png
✅ Processed and saved: h02-024.png
✅ Processed and saved: h02-028.png
✅ Processed and saved: h02-037.png
✅ Processed and saved: h02-040.png
✅ Processed and saved: h02-043.png
✅ Processed and saved: h02-035.png
✅ Processed and saved: h02-049.png
✅ Processed and saved: h04-007.png
✅ Processed and saved: h04-000.png
✅ Processed and saved: h04-021.png
✅ Processed and saved: h04-025.png
✅ Processed and saved: h04-028.png
✅ Processed and saved: h04-049.png
✅ Processed and saved: h04-035.png
✅ Processed and saved: h04-052.png
✅ Processed and saved: h04-057.png
✅ Processed and saved: h04-055.png
✅ Processed and saved: h04-071.png
✅ Processed and saved: h04-061.png
✅ Processed and saved: h04-074.png
✅ Processed and saved: h04-078.png
✅ Processed and saved: h05-012.png
✅ Processed and saved: h04-082.png
✅ Processed and saved: h06-000.png
✅ Processed and saved: h06-003.png
✅ Processed and saved: h06-079.png
✅ Processed and saved: h06-082.png
✅ Processed and saved: h06-085.png
✅ Processed and saved: h06-096.png
✅ Processed and saved: h06-089.png
✅ Processed and saved: h06-092.png
✅ Processed and saved: h07-000.png
✅ Processed and saved: h07-007 (1).png
✅ Processed and saved: h07-007.png
✅ Processed and saved: h07-003.png
✅ Processed and saved: h07-013.png
✅ Processed and saved: h07-011.png
✅ Processed and saved: h07-025.png
✅ Processed and saved: h07-020.png
✅ Processed and saved: h07-017.png
✅ Processed and saved: h07-025a.png
✅ Processed and saved: h07-023.png
✅ Processed and saved: h07-030.png
✅ Processed and saved: h07-028.png
✅ Processed and saved: h07-030a.png
✅ Processed and saved: h07-028a.png
✅ Processed and saved: h07-033.png
✅ Processed and saved: h07-033a.png
✅ Processed and saved: h07-037.png
✅ Processed and saved: h07-037a.png
✅ Processed and saved: h07-040b.png
✅ Processed and saved: h07-040.png
✅ Processed and saved: h07-044a.png
✅ Processed and saved: h07-054a.png
✅ Processed and saved: h07-051b.png
✅ Processed and saved: h07-060a.png
✅ Processed and saved: h07-063a.png
✅ Processed and saved: h07-060b.png
✅ Processed and saved: h07-057a.png
✅ Processed and saved: h07-066a.png
✅ Processed and saved: h07-063b.png
✅ Processed and saved: h07-066b.png
✅ Processed and saved: h07-069.png
✅ Processed and saved: h07-071.png
✅ Processed and saved: h07-069a.png
✅ Processed and saved: h07-075.png
✅ Processed and saved: h07-071a.png
✅ Processed and saved: h07-075a.png
✅ Processed and saved: h07-078a.png
✅ Processed and saved: h07-078.png
✅ Processed and saved: h07-080.png
✅ Processed and saved: h07-084.png
✅ Processed and saved: h07-080a.png
✅ Processed and saved: h07-087.png

In [16]:

preprocess_folder(
    input_folder="/content/drive/MyDrive/ComputerVision/formsI-Z",
    output_folder="/content/drive/MyDrive/ComputerVision/formsI-Z",
    binarize=True,
    use_bilateral=True
)

✅ Processed and saved: j01-042.png
✅ Processed and saved: j01-066.png
✅ Processed and saved: j01-045.png
✅ Processed and saved: j01-059.png
✅ Processed and saved: j01-063.png
✅ Processed and saved: j01-070.png
✅ Processed and saved: j01-049.png
✅ Processed and saved: j04-008.png
✅ Processed and saved: j04-012.png
✅ Processed and saved: j04-019.png
✅ Processed and saved: j04-024.png
✅ Processed and saved: j04-015.png
✅ Processed and saved: j04-039.png
✅ Processed and saved: j04-035.png
✅ Processed and saved: j04-046.png
✅ Processed and saved: j04-053.png
✅ Processed and saved: j04-065.png
✅ Processed and saved: j04-070.png
✅ Processed and saved: j04-061.png
✅ Processed and saved: j04-076.png
✅ Processed and saved: j04-098.png
✅ Processed and saved: j04-080.png
✅ Processed and saved: j04-094.png
✅ Processed and saved: j04-115.png
✅ Processed and saved: j06-005.png
✅ Processed and saved: j04-103.png
✅ Processed and saved: j06-000.png
✅ Processed and saved: j04-111.png
✅ Processed and saved: j06-014.png
✅ Processed and saved: j06-022.png
✅ Processed and saved: j06-018.png
✅ Processed and saved: j06-026.png
✅ Processed and saved: j06-008.png
✅ Processed and saved: j07-000.png
✅ Processed and saved: j06-056.png
✅ Processed and saved: j06-051.png
✅ Processed and saved: j06-030.png
✅ Processed and saved: j06-034.png
✅ Processed and saved: j07-005.png
✅ Processed and saved: j07-012.png
✅ Processed and saved: j07-015.png
✅ Processed and saved: k01-051.png
✅ Processed and saved: j07-009.png
✅ Processed and saved: k02-018.png
✅ Processed and saved: k02-029.png
✅ Processed and saved: k02-036.png
✅ Processed and saved: k02-023.png
✅ Processed and saved: k02-053.png
✅ Processed and saved: k02-062.png
✅ Processed and saved: k02-067.png
✅ Processed and saved: k02-093.png
✅ Processed and saved: k02-097.png
✅ Processed and saved: k02-076.png
✅ Processed and saved: k02-102.png
✅ Processed and saved: k03-117.png
✅ Processed and saved: k02-112.png
✅ Processed and saved: k02-117.png
✅ Processed and saved: k03-138.png
✅ Processed and saved: k03-144.png
✅ Processed and saved: k03-152.png
✅ Processed and saved: k03-157.png
✅ Processed and saved: k04-000.png
✅ Processed and saved: k03-164.png
✅ Processed and saved: k03-180.png
✅ Processed and saved: k04-014.png
✅ Processed and saved: k04-005.png
✅ Processed and saved: k04-010.png
✅ Processed and saved: k04-017.png
✅ Processed and saved: k04-022.png
✅ Processed and saved: k04-039.png
✅ Processed and saved: k04-028.png
✅ Processed and saved: k04-050.png
✅ Processed and saved: k04-033.png
✅ Processed and saved: k04-054.png
✅ Processed and saved: k04-061.png
✅ Processed and saved: k04-057.png
✅ Processed and saved: k04-068.png
✅ Processed and saved: k04-064.png
✅ Processed and saved: k04-079.png
✅ Processed and saved: k04-075.png
✅ Processed and saved: k04-085.png
✅ Processed and saved: k04-093.png
✅ Processed and saved: k04-099.png
✅ Processed and saved: k04-103.png
✅ Processed and saved: k04-106.png
✅ Processed and saved: k04-110.png
✅ Processed and saved: k04-115.png
✅ Processed and saved: k04-119.png
✅ Processed and saved: k04-126.png
✅ Processed and saved: k04-142.png
✅ Processed and saved: k04-136.png
✅ Processed and saved: k04-149.png
✅ Processed and saved: k04-156.png
✅ Processed and saved: k04-163.png
✅ Processed and saved: k07-063a.png
✅ Processed and saved: k07-059a.png
✅ Processed and saved: k07-067a.png
✅ Processed and saved: k07-077.png
✅ Processed and saved: k07-085.png
✅ Processed and saved: k07-122.png
✅ Processed and saved: k07-125.png
✅ Processed and saved: k07-134.png
✅ Processed and saved: k07-146.png
✅ Processed and saved: k07-152.png
✅ Processed and saved: k07-141.png
✅ Processed and saved: k07-158.png
✅ Processed and saved: k07-166.png
✅ Processed and saved: l01-000.png
✅ Processed and saved: k07-185.png
✅ Processed and saved: k07-176.png
✅ Processed and saved: l01-007.png
✅ Processed and saved: l01-016.png
✅ Processed and saved: l01-023.png
✅ Processed and saved: l01-030.png
✅ Processed and saved: l01-065.png
✅ Processed and saved: l01-050.png
✅ Processed and saved: l01-082.png
✅ Processed and saved: l01-095.png
✅ Processed and saved: l01-105.png
✅ Processed and saved: l01-111.png
✅ Processed and saved: l01-119.png
✅ Processed and saved: l01-129.png
✅ Processed and saved: l01-143.png
✅ Processed and saved: l01-133.png
✅ Processed and saved: l01-157.png
✅ Processed and saved: l01-179.png
✅ Processed and saved: l01-173.png
✅ Processed and saved: l01-187.png
✅ Processed and saved: l01-199.png
✅ Processed and saved: l01-195.png
✅ Processed and saved: l03-000.png
✅ Processed and saved: l03-004.png
✅ Processed and saved: l03-008.png
✅ Processed and saved: l04-000.png
✅ Processed and saved: l04-005.png
✅ Processed and saved: l04-012.png
✅ Processed and saved: l04-020.png
✅ Processed and saved: l04-026.png
✅ Processed and saved: l04-043.png
✅ Processed and saved: l04-052.png
✅ Processed and saved: l04-034.png
✅ Processed and saved: l04-062.png
✅ Processed and saved: l04-071.png
✅ Processed and saved: l04-066.png
✅ Processed and saved: l04-082.png
✅ Processed and saved: l04-093.png
✅ Processed and saved: l04-087.png
✅ Processed and saved: l04-098.png
✅ Processed and saved: l04-102.png
✅ Processed and saved: l04-113.png
✅ Processed and saved: l04-118.png
✅ Processed and saved: l04-106.png
✅ Processed and saved: l04-136.png
✅ Processed and saved: l04-130.png
✅ Processed and saved: l04-124.png
✅ Processed and saved: l04-141.png
✅ Processed and saved: l04-147.png
✅ Processed and saved: l04-153.png
✅ Processed and saved: l04-159.png
✅ Processed and saved: l04-170.png
✅ Processed and saved: l04-163.png
✅ Processed and saved: l04-174.png
✅ Processed and saved: l07-052.png
✅ Processed and saved: l04-179.png
✅ Processed and saved: l07-080.png
✅ Processed and saved: l07-074.png
✅ Processed and saved: l07-065.png
✅ Processed and saved: l07-111.png
✅ Processed and saved: l07-103.png
✅ Processed and saved: l07-118.png
✅ Processed and saved: l07-085.png
✅ Processed and saved: l07-135.png
✅ Processed and saved: l07-138.png
✅ Processed and saved: l07-131.png
✅ Processed and saved: l07-172.png
✅ Processed and saved: l07-181.png
✅ Processed and saved: l07-176.png
✅ Processed and saved: l07-187.png
✅ Processed and saved: l07-190.png
✅ Processed and saved: m01-000.png
✅ Processed and saved: m01-012.png
✅ Processed and saved: m01-022.png
✅ Processed and saved: m01-017.png
✅ Processed and saved: m01-026.png
✅ Processed and saved: m01-049.png
✅ Processed and saved: m01-038.png
✅ Processed and saved: m01-079.png
✅ Processed and saved: m01-032.png
✅ Processed and saved: m01-084.png
✅ Processed and saved: m01-090.png
✅ Processed and saved: m01-060.png
✅ Processed and saved: m01-095.png
✅ Processed and saved: m01-100.png
✅ Processed and saved: m01-110.png
✅ Processed and saved: m01-104.png
✅ Processed and saved: m01-115.png
✅ Processed and saved: m01-125.png
✅ Processed and saved: m01-131.png
✅ Processed and saved: m01-121.png
✅ Processed and saved: m01-149.png
✅ Processed and saved: m01-136.png
✅ Processed and saved: m01-160.png
✅ Processed and saved: m02-052.png
✅ Processed and saved: m02-048.png
✅ Processed and saved: m02-059.png
✅ Processed and saved: m02-066.png
✅ Processed and saved: m02-069.png
✅ Processed and saved: m02-055.png
✅ Processed and saved: m02-080.png
✅ Processed and saved: m02-072.png
✅ Processed and saved: m02-083.png
✅ Processed and saved: m02-075.png
✅ Processed and saved: m02-087.png
✅ Processed and saved: m02-095.png
✅ Processed and saved: m02-090.png
✅ Processed and saved: m02-102.png
✅ Processed and saved: m02-106.png
✅ Processed and saved: m03-006.png
✅ Processed and saved: m02-109.png
✅ Processed and saved: m02-112.png
✅ Processed and saved: m03-013.png
✅ Processed and saved: m03-020.png
✅ Processed and saved: m03-033.png
✅ Processed and saved: m03-095.png
✅ Processed and saved: m03-062.png
✅ Processed and saved: m03-110.png
✅ Processed and saved: m03-114.png
✅ Processed and saved: m03-118.png
✅ Processed and saved: m04-000.png
✅ Processed and saved: m04-007.png
✅ Processed and saved: m04-012.png
✅ Processed and saved: m04-019.png
✅ Processed and saved: m04-024.png
✅ Processed and saved: m04-038.png
✅ Processed and saved: m04-030.png
✅ Processed and saved: m04-043.png
✅ Processed and saved: m04-072.png
✅ Processed and saved: m04-061.png
✅ Processed and saved: m04-081.png
✅ Processed and saved: m04-078.png
✅ Processed and saved: m04-107.png
✅ Processed and saved: m04-100.png
✅ Processed and saved: m04-113.png
✅ Processed and saved: m04-093.png
✅ Processed and saved: m04-123.png
✅ Processed and saved: m04-131.png
✅ Processed and saved: m04-145.png
✅ Processed and saved: m04-164.png
✅ Processed and saved: m04-152.png
✅ Processed and saved: m04-138.png
✅ Processed and saved: m04-180.png
✅ Processed and saved: m04-209.png
✅ Processed and saved: m04-190.png
✅ Processed and saved: m04-200.png
✅ Processed and saved: m04-216.png
✅ Processed and saved: m04-222.png
✅ Processed and saved: m04-231.png
✅ Processed and saved: m04-238.png
✅ Processed and saved: m04-246.png
✅ Processed and saved: m06-019.png
✅ Processed and saved: m04-251.png
✅ Processed and saved: m06-031.png
✅ Processed and saved: m06-042.png
✅ Processed and saved: m06-048.png
✅ Processed and saved: m06-056.png
✅ Processed and saved: m06-067.png
✅ Processed and saved: m06-076.png
✅ Processed and saved: m06-083.png
✅ Processed and saved: m06-091.png
✅ Processed and saved: m06-106.png
✅ Processed and saved: n01-004.png
✅ Processed and saved: m06-098.png
✅ Processed and saved: n01-000.png
✅ Processed and saved: n01-020.png
✅ Processed and saved: n01-009.png
✅ Processed and saved: n01-045.png
✅ Processed and saved: n01-031.png
✅ Processed and saved: n01-036.png
✅ Processed and saved: n01-052.png
✅ Processed and saved: n01-057.png
✅ Processed and saved: n02-009.png
✅ Processed and saved: n02-004.png
✅ Processed and saved: n02-000.png
✅ Processed and saved: n02-016.png
✅ Processed and saved: n02-028.png
✅ Processed and saved: n02-033.png
✅ Processed and saved: n02-037.png
✅ Processed and saved: n02-040.png
✅ Processed and saved: n02-045.png
✅ Processed and saved: n02-049.png
✅ Processed and saved: n02-054.png
✅ Processed and saved: n02-082a.png
✅ Processed and saved: n02-062.png
✅ Processed and saved: n02-098.png
✅ Processed and saved: n02-104.png
✅ Processed and saved: n02-120.png
✅ Processed and saved: n02-109.png
✅ Processed and saved: n02-114.png
✅ Processed and saved: n02-127.png
✅ Processed and saved: n02-151.png
✅ Processed and saved: n02-146.png
✅ Processed and saved: n02-154.png
✅ Processed and saved: n02-157.png
✅ Processed and saved: n03-064.png
✅ Processed and saved: n03-038.png
✅ Processed and saved: n03-066.png
✅ Processed and saved: n03-079.png
✅ Processed and saved: n03-091.png
✅ Processed and saved: n03-082.png
✅ Processed and saved: n03-106.png
✅ Processed and saved: n03-103.png
✅ Processed and saved: n03-113.png
✅ Processed and saved: n03-097.png
✅ Processed and saved: n03-120.png
✅ Processed and saved: n03-126.png
✅ Processed and saved: n04-000.png
✅ Processed and saved: n04-009.png
✅ Processed and saved: n04-022.png
✅ Processed and saved: n04-015.png
✅ Processed and saved: n04-031.png
✅ Processed and saved: n04-044.png
✅ Processed and saved: n04-039.png
✅ Processed and saved: n04-048.png
✅ Processed and saved: n04-052.png
✅ Processed and saved: n04-068.png
✅ Processed and saved: n04-060.png
✅ Processed and saved: n04-092.png
✅ Processed and saved: n04-075.png
✅ Processed and saved: n04-084.png
✅ Processed and saved: n04-107.png
✅ Processed and saved: n04-100.png
✅ Processed and saved: n04-139.png
✅ Processed and saved: n04-149.png
✅ Processed and saved: n04-130.png
✅ Processed and saved: n04-114.png
✅ Processed and saved: n04-156.png
✅ Processed and saved: n04-171.png
✅ Processed and saved: n04-163.png
✅ Processed and saved: n04-190.png
✅ Processed and saved: n04-195.png
✅ Processed and saved: n04-183.png
✅ Processed and saved: n04-209.png
✅ Processed and saved: n04-202.png
✅ Processed and saved: n04-213.png
✅ Processed and saved: n04-218.png
✅ Processed and saved: n06-074.png
✅ Processed and saved: n06-082.png
✅ Processed and saved: n06-092.png
✅ Processed and saved: n06-100.png
✅ Processed and saved: n06-111.png
✅ Processed and saved: n06-119.png
✅ Processed and saved: n06-123.png
✅ Processed and saved: n06-133.png
✅ Processed and saved: n06-128.png
✅ Processed and saved: n06-148.png
✅ Processed and saved: n06-140.png
✅ Processed and saved: n06-156.png
✅ Processed and saved: n06-169.png
✅ Processed and saved: n06-163.png
✅ Processed and saved: n06-175.png
✅ Processed and saved: n06-194.png
✅ Processed and saved: n06-186.png
✅ Processed and saved: n06-182.png
✅ Processed and saved: p01-147.png
✅ Processed and saved: n06-201.png
✅ Processed and saved: p01-155.png
✅ Processed and saved: p01-168.png
✅ Processed and saved: p01-174.png
✅ Processed and saved: p02-000.png
✅ Processed and saved: p02-008.png
✅ Processed and saved: p02-017.png
✅ Processed and saved: p02-027.png
✅ Processed and saved: p02-022.png
✅ Processed and saved: p02-069.png
✅ Processed and saved: p02-090.png
✅ Processed and saved: p02-081.png
✅ Processed and saved: p02-076.png
✅ Processed and saved: p02-101.png
✅ Processed and saved: p02-105.png
✅ Processed and saved: p02-109.png
✅ Processed and saved: p02-121.png
✅ Processed and saved: p02-127.png
✅ Processed and saved: p02-115.png
✅ Processed and saved: p02-131.png
✅ Processed and saved: p02-135.png
✅ Processed and saved: p02-150.png
✅ Processed and saved: p02-144.png
✅ Processed and saved: p02-139.png
✅ Processed and saved: p03-004.png
✅ Processed and saved: p02-155.png
✅ Processed and saved: p03-009.png
✅ Processed and saved: p03-012.png
✅ Processed and saved: p03-023.png
✅ Processed and saved: p03-027.png
✅ Processed and saved: p03-029.png
✅ Processed and saved: p03-033.png
✅ Processed and saved: p03-047.png
✅ Processed and saved: p03-040.png
✅ Processed and saved: p03-057.png
✅ Processed and saved: p03-072.png
✅ Processed and saved: p03-080.png
✅ Processed and saved: p03-069.png
✅ Processed and saved: p03-087.png
✅ Processed and saved: p03-103.png
✅ Processed and saved: p03-096.png
✅ Processed and saved: p03-112.png
✅ Processed and saved: p03-135.png
✅ Processed and saved: p03-121.png
✅ Processed and saved: p03-142.png
✅ Processed and saved: p03-163.png
✅ Processed and saved: p03-151.png
✅ Processed and saved: p03-181.png
✅ Processed and saved: p03-173.png
✅ Processed and saved: p03-158.png
✅ Processed and saved: p03-189.png
✅ Processed and saved: p06-030.png
✅ Processed and saved: p06-042.png
✅ Processed and saved: p03-185.png
✅ Processed and saved: p06-047.png
✅ Processed and saved: p06-069.png
✅ Processed and saved: p06-052.png
✅ Processed and saved: p06-058.png
✅ Processed and saved: p06-088.png
✅ Processed and saved: p06-096.png
✅ Processed and saved: p06-242.png
✅ Processed and saved: p06-104.png
✅ Processed and saved: p06-248.png
✅ Processed and saved: r02-003.png
✅ Processed and saved: r02-000.png
✅ Processed and saved: r02-013.png
✅ Processed and saved: r02-006.png
✅ Processed and saved: r02-010.png
✅ Processed and saved: r02-060.png
✅ Processed and saved: r02-054.png
✅ Processed and saved: r02-038.png
✅ Processed and saved: r02-065.png
✅ Processed and saved: r02-078.png
✅ Processed and saved: r02-081.png
✅ Processed and saved: r02-070.png
✅ Processed and saved: r02-109.png
✅ Processed and saved: r02-089.png
✅ Processed and saved: r02-127.png
✅ Processed and saved: r02-117.png
✅ Processed and saved: r02-131.png
✅ Processed and saved: r02-137.png
✅ Processed and saved: r02-146.png
✅ Processed and saved: r03-002.png
✅ Processed and saved: r03-007.png
✅ Processed and saved: r03-026.png
✅ Processed and saved: r03-030.png
✅ Processed and saved: r03-035.png
✅ Processed and saved: r03-053.png
✅ Processed and saved: r03-050.png
✅ Processed and saved: r03-065.png
✅ Processed and saved: r03-084.png
✅ Processed and saved: r03-056.png
✅ Processed and saved: r03-090.png
✅ Processed and saved: r03-110.png
✅ Processed and saved: r03-115.png
✅ Processed and saved: r03-096.png
✅ Processed and saved: r06-000.png
✅ Processed and saved: r06-003.png
✅ Processed and saved: r06-007.png
✅ Processed and saved: r06-011.png
✅ Processed and saved: r06-018.png
✅ Processed and saved: r06-027.png
✅ Processed and saved: r06-022.png
✅ Processed and saved: r06-035.png
✅ Processed and saved: r06-041.png
✅ Processed and saved: r06-044.png
✅ Processed and saved: r06-049.png
✅ Processed and saved: r06-053.png
✅ Processed and saved: r06-057.png
✅ Processed and saved: r06-062.png
✅ Processed and saved: r06-066.png
✅ Processed and saved: r06-070.png
✅ Processed and saved: r06-097.png
✅ Processed and saved: r06-090.png
✅ Processed and saved: r06-076.png
✅ Processed and saved: r06-103.png
✅ Processed and saved: r06-111.png
✅ Processed and saved: r06-106.png
✅ Processed and saved: r06-115.png
✅ Processed and saved: r06-130.png
✅ Processed and saved: r06-137.png
✅ Processed and saved: r06-126.png
✅ Processed and saved: r06-121.png
✅ Processed and saved: r06-143.png

## Creating Dataframe

In [4]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/ComputerVision/VisionSpeak/Handwriting_1_matadata.csv")

In [5]:
df

,form_id,image_path,transcription
0,a01-000u,/content/drive/MyDrive/ComputerVision/formsA-D...,A MOVE to stop Mr. Gaitskell from nominating a...
1,a01-000x,/content/drive/MyDrive/ComputerVision/formsA-D...,A MOVE to stop Mr. Gaitskell from nominating a...
2,a01-003,/content/drive/MyDrive/ComputerVision/formsA-D...,Though they may gather some Left-wing support ...
3,a01-003u,/content/drive/MyDrive/ComputerVision/formsA-D...,Though they may gather some Left-wing support ...
4,a01-003x,/content/drive/MyDrive/ComputerVision/formsA-D...,Though they may gather some Left-wing support ...
...,...,...,...
1534,r06-121,/content/drive/MyDrive/ComputerVision/formsI-Z...,"At the school , which is charming , ci- vilise..."
1535,r06-126,/content/drive/MyDrive/ComputerVision/formsI-Z...,For his sake we chose the more serious of the ...
1536,r06-130,/content/drive/MyDrive/ComputerVision/formsI-Z...,At the entrance of the cinema the doorman was ...
1537,r06-137,/content/drive/MyDrive/ComputerVision/formsI-Z...,The doorman turned his attention to the next r...
1538,r06-143,/content/drive/MyDrive/ComputerVision/formsI-Z...,In the train going back to London I sat beside...

## Merging two dataframes

In [6]:
df = pd.concat([df, sentence_df], axis=0)

In [7]:
df

,form_id,image_path,transcription
0,a01-000u,/content/drive/MyDrive/ComputerVision/formsA-D...,A MOVE to stop Mr. Gaitskell from nominating a...
1,a01-000x,/content/drive/MyDrive/ComputerVision/formsA-D...,A MOVE to stop Mr. Gaitskell from nominating a...
2,a01-003,/content/drive/MyDrive/ComputerVision/formsA-D...,Though they may gather some Left-wing support ...
3,a01-003u,/content/drive/MyDrive/ComputerVision/formsA-D...,Though they may gather some Left-wing support ...
4,a01-003x,/content/drive/MyDrive/ComputerVision/formsA-D...,Though they may gather some Left-wing support ...
...,...,...,...
16747,r06-143-s01-01,/content/drive/MyDrive/ComputerVision/sentence...,"in front of her , but she said :"
16748,r06-143-s02-00,/content/drive/MyDrive/ComputerVision/sentence...,' Philip 's awfully lucky .
16749,r06-143-s03-00,/content/drive/MyDrive/ComputerVision/sentence...,I wish I went to that school .
16750,r06-143-s04-00,/content/drive/MyDrive/ComputerVision/sentence...,Did you notice
16751,r06-143-s04-01,/content/drive/MyDrive/ComputerVision/sentence...,that girl who said hullo to him in the garden ?

In [8]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/ComputerVision/VisionSpeak/Handwriting_1_matadata.csv")
df.to_csv('/content/drive/MyDrive/ComputerVision/VisionSpeak/Handwriting_1_matadata.csv', index=False)

In [9]:
df

,form_id,image_path,transcription
0,a01-000u,/content/drive/MyDrive/ComputerVision/formsA-D...,A MOVE to stop Mr. Gaitskell from nominating a...
1,a01-000x,/content/drive/MyDrive/ComputerVision/formsA-D...,A MOVE to stop Mr. Gaitskell from nominating a...
2,a01-003,/content/drive/MyDrive/ComputerVision/formsA-D...,Though they may gather some Left-wing support ...
3,a01-003u,/content/drive/MyDrive/ComputerVision/formsA-D...,Though they may gather some Left-wing support ...
4,a01-003x,/content/drive/MyDrive/ComputerVision/formsA-D...,Though they may gather some Left-wing support ...
...,...,...,...
1534,r06-121,/content/drive/MyDrive/ComputerVision/formsI-Z...,"At the school , which is charming , ci- vilise..."
1535,r06-126,/content/drive/MyDrive/ComputerVision/formsI-Z...,For his sake we chose the more serious of the ...
1536,r06-130,/content/drive/MyDrive/ComputerVision/formsI-Z...,At the entrance of the cinema the doorman was ...
1537,r06-137,/content/drive/MyDrive/ComputerVision/formsI-Z...,The doorman turned his attention to the next r...
1538,r06-143,/content/drive/MyDrive/ComputerVision/formsI-Z...,In the train going back to London I sat beside...

### Tokenization

In [10]:
import pandas as pd

class OCRTokenizer:
    def __init__(self, text_column='transcription'):
        text_data = "".join(df[text_column].astype(str).tolist())

        self.text_column = text_column
        self.vocab = sorted(set(text_data))
        self.char2idx = {char: idx + 1 for idx, char in enumerate(self.vocab)}  # Start from 1
        self.char2idx['[BLANK]'] = 0  # CTC blank token

        self.idx2char = {idx: char for char, idx in self.char2idx.items()}

    def encode(self, text):
        return [self.char2idx[char] for char in text if char in self.char2idx]

    def decode(self, indices):
        return "".join([self.idx2char.get(idx, '') for idx in indices if idx > 0])

    def __len__(self):
        return len(self.char2idx)


def tokenize_dataset_csv(csv_path, tokenizer, text_column="transcription", save_as=None):
    """
    Tokenizes the entire dataset using the tokenizer.
    Adds 'encoded_label' column and optionally saves to disk.
    """
    df = pd.read_csv(csv_path)

    if text_column not in df.columns:
        raise ValueError(f"❌ Column '{text_column}' not found in CSV.")

    df['encoded_label'] = df[text_column].astype(str).apply(tokenizer.encode)

    if save_as:
        df.to_csv(save_as, index=False)
        print(f"✅ Tokenized CSV saved to: {save_as}")

    return df

In [11]:

tokenizer = OCRTokenizer(text_column="transcription")

tokenized_df = tokenize_dataset_csv(
    "/content/drive/MyDrive/ComputerVision/VisionSpeak/Sentence_Metadata.csv",
    tokenizer,
    text_column="transcription",
    save_as="/content/drive/MyDrive/ComputerVision/VisionSpeak/Handwriting_1_tokenized.csv"
)

✅ Tokenized CSV saved to: /content/drive/MyDrive/ComputerVision/VisionSpeak/Handwriting_1_tokenized.csv

### Train and validation set splits

In [12]:
import pandas as pd
import os
import random

def split_dataset_csv(
    csv_path,
    train_csv_path,
    test_csv_path,
    split_ratio=0.8,
    shuffle=True,
    seed=42
):
    """
    Split a labeled dataset CSV into train/test.
    """
    df = pd.read_csv(csv_path)

    if shuffle:
        df = df.sample(frac=1, random_state=seed).reset_index(drop=True)

    split_index = int(len(df) * split_ratio)
    train_df = df.iloc[:split_index]
    test_df = df.iloc[split_index:]

    train_df.to_csv(train_csv_path, index=False)
    test_df.to_csv(test_csv_path, index=False)

    print(f"Train: {len(train_df)} samples")
    print(f"Test:  {len(test_df)} samples")

In [13]:
split_dataset_csv(
    csv_path="/content/drive/MyDrive/ComputerVision/VisionSpeak/Handwriting_1_tokenized.csv",
    train_csv_path="/content/drive/MyDrive/ComputerVision/VisionSpeak/train.csv",
    test_csv_path="/content/drive/MyDrive/ComputerVision/VisionSpeak/test.csv",
    split_ratio=0.9
)

Train: 15076 samples
Test:  1676 samples

### Creating Dataloder

In [32]:
import torch
from torch.utils.data import Dataset, DataLoader
import cv2
import numpy as np
import pandas as pd
import ast

class OCRDataset(Dataset):
    def __init__(self, csv_path):
        self.df = pd.read_csv(csv_path)

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img_path = row["image_path"]
        label_encoded = ast.literal_eval(row["encoded_label"])



        img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        if img is None:
            raise FileNotFoundError(f"Image not found: {img_path}")

        ########################shreya

        # Resize all to fixed size (128 height x 512 width)
        # img = cv2.resize(img, (512, 128))
        # img = cv2.resize(img, (2048, 128))
        img = cv2.resize(img, (3072, 128))  # Boost time steps

        ###########################

        # Images are already resized/padded — no resize here
        img = img.astype(np.float32) / 255.0
        img = np.expand_dims(img, axis=0)  # [1, H, W]

        return {
            "image": torch.tensor(img, dtype=torch.float32),
            "label": torch.tensor(label_encoded, dtype=torch.long),
            "label_length": len(label_encoded),
            "img_path": img_path
        }

def ctc_collate_fn(batch):
    images = [item["image"] for item in batch]
    labels = [item["label"] for item in batch]

    image_batch = torch.stack(images)
    label_lengths = torch.tensor([len(label) for label in labels], dtype=torch.long)
    padded_labels = torch.nn.utils.rnn.pad_sequence(labels, batch_first=True, padding_value=0)

    return {
        "images": image_batch,
        "labels": padded_labels,
        "label_lengths": label_lengths,
    }

# === Usage ===
train_csv_path = "/content/drive/MyDrive/ComputerVision/VisionSpeak/train.csv"
test_csv_path  = "/content/drive/MyDrive/ComputerVision/VisionSpeak/test.csv"

train_dataset = OCRDataset(train_csv_path)
test_dataset  = OCRDataset(test_csv_path)

train_loader = DataLoader(train_dataset, batch_size=2, shuffle=True, collate_fn=ctc_collate_fn)
test_loader  = DataLoader(test_dataset, batch_size=2, shuffle=False, collate_fn=ctc_collate_fn)

print("✅ DataLoaders ready!")
print("🔢 Train size:", len(train_dataset))
print("🔢 Test size:", len(test_dataset))

✅ DataLoaders ready!
🔢 Train size: 15076
🔢 Test size: 1676

## Modelling

In [33]:
import torch

if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

print(f"✅ Using device: {device}")

✅ Using device: cpu

#### Baseline 1 Model:

In [34]:
# from transformers import TrOCRProcessor, VisionEncoderDecoderModel
# from torch.utils.data import Dataset, DataLoader
# import pandas as pd
# import torch
# from PIL import Image

# # === TrOCR Dataset ===
# class TrOCRDataset(Dataset):
#     def __init__(self, csv_path, processor):
#         self.df = pd.read_csv(csv_path)
#         self.processor = processor

#     def __len__(self):
#         return len(self.df)

#     def __getitem__(self, idx):
#         row = self.df.iloc[idx]
#         img = Image.open(row['image_path']).convert("RGB")
#         pixel_values = self.processor(images=img, return_tensors="pt").pixel_values.squeeze(0)

#         return {
#             'pixel_values': pixel_values,
#             'text': row['transcription']  # fixed here
#         }

# # === Collate Function ===
# def trocr_collate_fn(batch, processor):
#     pixel_values = torch.stack([item['pixel_values'] for item in batch])
#     texts = [item['text'] for item in batch]
#     labels = processor.tokenizer(texts, padding="longest", return_tensors="pt").input_ids
#     labels[labels == processor.tokenizer.pad_token_id] = -100  # For CrossEntropyLoss
#     return {'pixel_values': pixel_values, 'labels': labels}

# # === Load Pretrained Model and Processor ===
# processor = TrOCRProcessor.from_pretrained("microsoft/trocr-base-handwritten")
# model = VisionEncoderDecoderModel.from_pretrained("microsoft/trocr-base-handwritten")
# model.config.decoder_start_token_id = processor.tokenizer.bos_token_id
# model.config.pad_token_id = processor.tokenizer.pad_token_id
# device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")
# model.to(device)

# # === DataLoader ===
# train_dataset = TrOCRDataset("/content/drive/MyDrive/ComputerVision/VisionSpeak/train.csv", processor)
# test_dataset = TrOCRDataset("/content/drive/MyDrive/ComputerVision/VisionSpeak/test.csv", processor)

# train_loader = DataLoader(train_dataset, batch_size=2, shuffle=True,
#                           collate_fn=lambda x: trocr_collate_fn(x, processor))
# test_loader = DataLoader(test_dataset, batch_size=2, shuffle=False,
#                          collate_fn=lambda x: trocr_collate_fn(x, processor))

# # === Training Loop ===
# from torch import nn
# # from transformers import AdamW
# from torch.optim import AdamW



# optimizer = AdamW(model.parameters(), lr=5e-5)
# loss_fn = nn.CrossEntropyLoss(ignore_index=-100)

# for epoch in range(3):
#     model.train()
#     total_loss = 0
#     for batch in train_loader:
#         pixel_values = batch['pixel_values'].to(device)
#         labels = batch['labels'].to(device)

#         outputs = model(pixel_values=pixel_values, labels=labels)
#         loss = outputs.loss
#         loss.backward()

#         optimizer.step()
#         optimizer.zero_grad()

#         total_loss += loss.item()

#     model.eval()
#     val_loss = 0
#     with torch.no_grad():
#         for batch in test_loader:
#             pixel_values = batch['pixel_values'].to(device)
#             labels = batch['labels'].to(device)

#             outputs = model(pixel_values=pixel_values, labels=labels)
#             loss = outputs.loss
#             val_loss += loss.item()

#     print(f" Epoch {epoch+1} —  Train Loss: {total_loss / len(train_loader):.4f} |  Val Loss: {val_loss / len(test_loader):.4f}")

# print("TrOCR Baseline training complete!")

In [35]:
# from PIL import Image
# import matplotlib.pyplot as plt
# import random
# import pandas as pd

# df = pd.read_csv("/content/drive/MyDrive/ComputerVision/VisionSpeak/Sentence_Metadata.csv")
# sample = df.sample(5)

# for _, row in sample.iterrows():
#     img = Image.open(row['image_path']).convert("RGB")
#     plt.imshow(img)
#     plt.title(row['transcription'])
#     plt.axis("off")
#     plt.show()

## Baseline2 - Baseline 1 Model: ResNet-100 + CRNN + BiLSTM + CTC

In [36]:
import torch
import torch.nn as nn
import torchvision.models as models

### Model Defination

In [37]:
class CRNN_OCR(nn.Module):
    def __init__(self, num_classes):
        super(CRNN_OCR, self).__init__()

        # === Feature Extractor: ResNet-50 (remove last FC layer) ===
        resnet = models.resnet50(pretrained=True)
        modules = list(resnet.children())[:-3]  # Keep up to conv4_x
        self.cnn = nn.Sequential(*modules)

        # === Reshape to sequence ===
        self.adaptive_pool = nn.AdaptiveAvgPool2d((1, None))  # Height=1, variable width

        # === Sequence model ===
        self.rnn = nn.LSTM(
            input_size=1024,  # From ResNet conv4_x output
            hidden_size=256,
            num_layers=2,
            bidirectional=True,
            batch_first=True
        )

        # === Output Layer ===
        self.fc = nn.Linear(512, num_classes)  # 256 * 2 (BiLSTM)

    def forward(self, x):
        # Input: [B, 1, H, W] → ResNet expects 3 channels
        x = x.repeat(1, 3, 1, 1)  # Convert grayscale to 3-channel

        features = self.cnn(x)  # [B, 1024, H, W]
        features = self.adaptive_pool(features)  # [B, 1024, 1, W]
        features = features.squeeze(2)  # [B, 1024, W]

        # Transpose to [B, W, 1024]
        features = features.permute(0, 2, 1)

        rnn_out, _ = self.rnn(features)  # [B, W, 512]
        output = self.fc(rnn_out)        # [B, W, num_classes]
        output = output.permute(1, 0, 2)  # [W, B, num_classes] for CTC Loss

        return output

### Model Loss and optimization setup

In [38]:
vocab_size = len(tokenizer)
model_crnn = CRNN_OCR(num_classes=vocab_size).to(device)

ctc_loss_fn = nn.CTCLoss(blank=0, zero_infinity=True)
optimizer_crnn = torch.optim.AdamW(model_crnn.parameters(), lr=1e-4)

/usr/local/lib/python3.11/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)

### Training Loop

In [ ]:
num_epochs = 3

for epoch in range(num_epochs):
    model_crnn.train()
    total_train_loss = 0

    for batch in train_loader:
        images = batch["images"].to(device)
        labels = batch["labels"].to(device)
        label_lengths = batch["label_lengths"].to(device)

        logits = model_crnn(images)  # [W, B, C]
        input_lengths = torch.full(size=(logits.size(1),), fill_value=logits.size(0), dtype=torch.long).to(device)
        # targets = labels.view(-1)

        # print(f"🖼️ Image input size: {images.shape}")   # [B, 1, H, W]
        # print(f"🧠 Logits shape (seq_len, B, C): {logits.shape}")
        # print(f"📝 Max target length: {label_lengths.max()}")
        # break  # just run one batch

        # min_required_len = (2 * label_lengths.max() - 1).item()

        # # if logits.shape[0] < min_required_len:
        # #     print(f"⏭️ Skipping batch: time_steps={logits.shape[0]}, required>={min_required_len}")
        # #     continue

        # ✅ Correct target build (no pad tokens)
        targets = torch.cat([labels[i][:label_lengths[i]] for i in range(len(labels))]).to(device)
        print("🎯 Target length (flattened):", targets.shape[0])

        log_probs = torch.nn.functional.log_softmax(logits, dim=2)

        loss = ctc_loss_fn(log_probs, targets, input_lengths, label_lengths)

        optimizer_crnn.zero_grad()
        print("🔁 CTC Loss:", loss.item())

        loss.backward()
        optimizer_crnn.step()




        total_train_loss += loss.item()

    print(f"[Epoch {epoch+1}] Train Loss: {total_train_loss / len(train_loader):.4f}")

🎯 Target length (flattened): 69
🔁 CTC Loss: 22.234966278076172
🎯 Target length (flattened): 105
🔁 CTC Loss: 14.940831184387207
🎯 Target length (flattened): 54
🔁 CTC Loss: 28.649139404296875
🎯 Target length (flattened): 19
🔁 CTC Loss: 83.20243835449219
🎯 Target length (flattened): 44
🔁 CTC Loss: 42.384239196777344
🎯 Target length (flattened): 50
🔁 CTC Loss: 38.05339431762695
🎯 Target length (flattened): 77
🔁 CTC Loss: 17.808834075927734
🎯 Target length (flattened): 63
🔁 CTC Loss: 25.66033172607422
🎯 Target length (flattened): 92
🔁 CTC Loss: 14.860563278198242
🎯 Target length (flattened): 46
🔁 CTC Loss: 34.848060607910156
🎯 Target length (flattened): 49
🔁 CTC Loss: 48.58294677734375
🎯 Target length (flattened): 120
🔁 CTC Loss: 11.841283798217773
🎯 Target length (flattened): 23
🔁 CTC Loss: 64.22191619873047
🎯 Target length (flattened): 106
🔁 CTC Loss: 12.807843208312988
🎯 Target length (flattened): 54
🔁 CTC Loss: 29.776256561279297
🎯 Target length (flattened): 51
🔁 CTC Loss: 43.553871154785156
🎯 Target length (flattened): 92
🔁 CTC Loss: 13.148667335510254
🎯 Target length (flattened): 75
🔁 CTC Loss: 17.043453216552734
🎯 Target length (flattened): 85
🔁 CTC Loss: 13.760906219482422
🎯 Target length (flattened): 85
🔁 CTC Loss: 13.83858871459961
🎯 Target length (flattened): 93
🔁 CTC Loss: 11.63221263885498
🎯 Target length (flattened): 55
🔁 CTC Loss: 19.47954559326172
🎯 Target length (flattened): 56
🔁 CTC Loss: 18.067943572998047
🎯 Target length (flattened): 69
🔁 CTC Loss: 13.783340454101562
🎯 Target length (flattened): 55
🔁 CTC Loss: 22.7730712890625
🎯 Target length (flattened): 48
🔁 CTC Loss: 23.692005157470703
🎯 Target length (flattened): 82
🔁 CTC Loss: 8.574106216430664
🎯 Target length (flattened): 74
🔁 CTC Loss: 8.646753311157227
🎯 Target length (flattened): 76
🔁 CTC Loss: 7.698237419128418
🎯 Target length (flattened): 56
🔁 CTC Loss: 8.896862983703613
🎯 Target length (flattened): 77
🔁 CTC Loss: 6.40384578704834
🎯 Target length (flattened): 89
🔁 CTC Loss: 5.684028625488281
🎯 Target length (flattened): 80
🔁 CTC Loss: 5.642234802246094
🎯 Target length (flattened): 77
🔁 CTC Loss: 4.986126899719238
🎯 Target length (flattened): 19
🔁 CTC Loss: 12.50738525390625
🎯 Target length (flattened): 50
🔁 CTC Loss: 24.046295166015625
🎯 Target length (flattened): 54
🔁 CTC Loss: 6.000255584716797
🎯 Target length (flattened): 97
🔁 CTC Loss: 4.126901626586914
🎯 Target length (flattened): 75
🔁 CTC Loss: 4.125021934509277
🎯 Target length (flattened): 72
🔁 CTC Loss: 4.198336601257324
🎯 Target length (flattened): 61
🔁 CTC Loss: 4.44533634185791
🎯 Target length (flattened): 105
🔁 CTC Loss: 4.269451141357422
🎯 Target length (flattened): 83
🔁 CTC Loss: 4.324371337890625
🎯 Target length (flattened): 57
🔁 CTC Loss: 4.234429359436035
🎯 Target length (flattened): 78
🔁 CTC Loss: 4.2873687744140625
🎯 Target length (flattened): 90
🔁 CTC Loss: 4.445401191711426
🎯 Target length (flattened): 91
🔁 CTC Loss: 4.394983768463135
🎯 Target length (flattened): 38
🔁 CTC Loss: 12.947406768798828
🎯 Target length (flattened): 85
🔁 CTC Loss: 4.40131950378418
🎯 Target length (flattened): 92
🔁 CTC Loss: 4.5710859298706055
🎯 Target length (flattened): 121
🔁 CTC Loss: 4.875153064727783
🎯 Target length (flattened): 63
🔁 CTC Loss: 4.420637607574463
🎯 Target length (flattened): 83
🔁 CTC Loss: 4.592944145202637
🎯 Target length (flattened): 38
🔁 CTC Loss: 4.479707717895508
🎯 Target length (flattened): 92
🔁 CTC Loss: 4.6760945320129395
🎯 Target length (flattened): 89
🔁 CTC Loss: 4.756887435913086
🎯 Target length (flattened): 43
🔁 CTC Loss: 4.298018455505371
🎯 Target length (flattened): 70
🔁 CTC Loss: 4.477041244506836
🎯 Target length (flattened): 77
🔁 CTC Loss: 4.522993087768555
🎯 Target length (flattened): 71
🔁 CTC Loss: 4.657676696777344
🎯 Target length (flattened): 65
🔁 CTC Loss: 4.462555408477783
🎯 Target length (flattened): 52
🔁 CTC Loss: 4.183989524841309
🎯 Target length (flattened): 83
🔁 CTC Loss: 4.628787040710449
🎯 Target length (flattened): 77
🔁 CTC Loss: 4.401552677154541
🎯 Target length (flattened): 19
🔁 CTC Loss: 5.111501693725586
🎯 Target length (flattened): 35
🔁 CTC Loss: 4.54057502746582
🎯 Target length (flattened): 85
🔁 CTC Loss: 4.600020408630371
🎯 Target length (flattened): 33
🔁 CTC Loss: 4.126059055328369
🎯 Target length (flattened): 81
🔁 CTC Loss: 4.4880218505859375
🎯 Target length (flattened): 53
🔁 CTC Loss: 4.1455488204956055
🎯 Target length (flattened): 56
🔁 CTC Loss: 4.293283939361572
🎯 Target length (flattened): 78
🔁 CTC Loss: 4.446135520935059
🎯 Target length (flattened): 59
🔁 CTC Loss: 4.2386884689331055
🎯 Target length (flattened): 82
🔁 CTC Loss: 4.43143367767334
🎯 Target length (flattened): 75
🔁 CTC Loss: 4.383951187133789
🎯 Target length (flattened): 69
🔁 CTC Loss: 4.145706653594971
🎯 Target length (flattened): 66
🔁 CTC Loss: 4.144674301147461
🎯 Target length (flattened): 48
🔁 CTC Loss: 4.283526420593262
🎯 Target length (flattened): 49
🔁 CTC Loss: 3.9991776943206787
🎯 Target length (flattened): 44
🔁 CTC Loss: 4.758260726928711
🎯 Target length (flattened): 76
🔁 CTC Loss: 4.172562599182129
🎯 Target length (flattened): 86
🔁 CTC Loss: 4.252211093902588
🎯 Target length (flattened): 68
🔁 CTC Loss: 4.095747470855713
🎯 Target length (flattened): 45
🔁 CTC Loss: 4.083759784698486
🎯 Target length (flattened): 98
🔁 CTC Loss: 4.232834815979004
🎯 Target length (flattened): 81
🔁 CTC Loss: 4.078496932983398
🎯 Target length (flattened): 39
🔁 CTC Loss: 4.78938102722168
🎯 Target length (flattened): 81
🔁 CTC Loss: 3.9692487716674805
🎯 Target length (flattened): 93
🔁 CTC Loss: 4.178537845611572
🎯 Target length (flattened): 59
🔁 CTC Loss: 3.8364486694335938
🎯 Target length (flattened): 95
🔁 CTC Loss: 4.1508941650390625
🎯 Target length (flattened): 55
🔁 CTC Loss: 4.085501670837402
🎯 Target length (flattened): 35
🔁 CTC Loss: 3.8609843254089355
🎯 Target length (flattened): 89
🔁 CTC Loss: 4.067496299743652
🎯 Target length (flattened): 71
🔁 CTC Loss: 3.9977517127990723
🎯 Target length (flattened): 48
🔁 CTC Loss: 3.814162254333496
🎯 Target length (flattened): 91
🔁 CTC Loss: 4.027587890625
🎯 Target length (flattened): 16
🔁 CTC Loss: 4.801006317138672
🎯 Target length (flattened): 74
🔁 CTC Loss: 3.80283784866333
🎯 Target length (flattened): 53
🔁 CTC Loss: 4.905263900756836
🎯 Target length (flattened): 66
🔁 CTC Loss: 3.690300703048706
🎯 Target length (flattened): 80
🔁 CTC Loss: 3.900069236755371
🎯 Target length (flattened): 73
🔁 CTC Loss: 3.7809946537017822
🎯 Target length (flattened): 74
🔁 CTC Loss: 3.7924623489379883
🎯 Target length (flattened): 93
🔁 CTC Loss: 3.893251657485962
🎯 Target length (flattened): 67
🔁 CTC Loss: 3.7220964431762695
🎯 Target length (flattened): 69
🔁 CTC Loss: 3.7825021743774414
🎯 Target length (flattened): 72
🔁 CTC Loss: 3.788595199584961
🎯 Target length (flattened): 64
🔁 CTC Loss: 4.248365879058838
🎯 Target length (flattened): 56
🔁 CTC Loss: 3.6799020767211914
🎯 Target length (flattened): 50
🔁 CTC Loss: 4.202946186065674
🎯 Target length (flattened): 78
🔁 CTC Loss: 3.7476704120635986
🎯 Target length (flattened): 74
🔁 CTC Loss: 3.716388702392578
🎯 Target length (flattened): 84
🔁 CTC Loss: 3.751340627670288
🎯 Target length (flattened): 92
🔁 CTC Loss: 3.875511646270752
🎯 Target length (flattened): 87
🔁 CTC Loss: 3.6795542240142822
🎯 Target length (flattened): 94
🔁 CTC Loss: 3.772341012954712
🎯 Target length (flattened): 52
🔁 CTC Loss: 3.7560207843780518
🎯 Target length (flattened): 48
🔁 CTC Loss: 5.777490615844727
🎯 Target length (flattened): 26
🔁 CTC Loss: 9.09814739227295
🎯 Target length (flattened): 61
🔁 CTC Loss: 3.946411371231079
🎯 Target length (flattened): 71
🔁 CTC Loss: 3.5332558155059814
🎯 Target length (flattened): 48
🔁 CTC Loss: 6.593042850494385
🎯 Target length (flattened): 50
🔁 CTC Loss: 3.7817225456237793
🎯 Target length (flattened): 51
🔁 CTC Loss: 3.765085220336914
🎯 Target length (flattened): 80
🔁 CTC Loss: 3.814606189727783
🎯 Target length (flattened): 42
🔁 CTC Loss: 3.915360450744629
🎯 Target length (flattened): 73
🔁 CTC Loss: 3.728395938873291
🎯 Target length (flattened): 94
🔁 CTC Loss: 3.881770133972168
🎯 Target length (flattened): 96
🔁 CTC Loss: 3.9373130798339844
🎯 Target length (flattened): 64
🔁 CTC Loss: 3.6173837184906006
🎯 Target length (flattened): 78
🔁 CTC Loss: 3.812079906463623
🎯 Target length (flattened): 65
🔁 CTC Loss: 3.7786173820495605
🎯 Target length (flattened): 79
🔁 CTC Loss: 3.8661231994628906
🎯 Target length (flattened): 64
🔁 CTC Loss: 3.749879837036133
🎯 Target length (flattened): 57
🔁 CTC Loss: 4.116289138793945
🎯 Target length (flattened): 38
🔁 CTC Loss: 3.844609022140503
🎯 Target length (flattened): 69
🔁 CTC Loss: 3.7316882610321045
🎯 Target length (flattened): 86
🔁 CTC Loss: 3.8710989952087402
🎯 Target length (flattened): 72
🔁 CTC Loss: 3.7491753101348877
🎯 Target length (flattened): 88
🔁 CTC Loss: 3.925659656524658
🎯 Target length (flattened): 73
🔁 CTC Loss: 3.7126712799072266
🎯 Target length (flattened): 46
🔁 CTC Loss: 3.6192209720611572
🎯 Target length (flattened): 85
🔁 CTC Loss: 3.78714656829834
🎯 Target length (flattened): 46
🔁 CTC Loss: 5.919928550720215
🎯 Target length (flattened): 84
🔁 CTC Loss: 3.64785099029541
🎯 Target length (flattened): 88
🔁 CTC Loss: 3.7152507305145264
🎯 Target length (flattened): 64
🔁 CTC Loss: 3.7362613677978516
🎯 Target length (flattened): 71
🔁 CTC Loss: 3.754101037979126
🎯 Target length (flattened): 47
🔁 CTC Loss: 7.917999267578125
🎯 Target length (flattened): 56
🔁 CTC Loss: 3.887436866760254
🎯 Target length (flattened): 68
🔁 CTC Loss: 3.8448328971862793
🎯 Target length (flattened): 81
🔁 CTC Loss: 3.7935104370117188
🎯 Target length (flattened): 81
🔁 CTC Loss: 3.746967315673828
🎯 Target length (flattened): 121
🔁 CTC Loss: 3.933023452758789
🎯 Target length (flattened): 58
🔁 CTC Loss: 3.8467187881469727
🎯 Target length (flattened): 80
🔁 CTC Loss: 3.7696738243103027
🎯 Target length (flattened): 70
🔁 CTC Loss: 3.555291175842285
🎯 Target length (flattened): 66
🔁 CTC Loss: 3.5866546630859375
🎯 Target length (flattened): 69
🔁 CTC Loss: 3.55889892578125
🎯 Target length (flattened): 42
🔁 CTC Loss: 5.820580959320068
🎯 Target length (flattened): 87
🔁 CTC Loss: 3.6931164264678955
🎯 Target length (flattened): 99
🔁 CTC Loss: 3.8117823600769043
🎯 Target length (flattened): 46
🔁 CTC Loss: 3.4627275466918945
🎯 Target length (flattened): 68
🔁 CTC Loss: 4.104037761688232
🎯 Target length (flattened): 93
🔁 CTC Loss: 3.7561206817626953
🎯 Target length (flattened): 51
🔁 CTC Loss: 3.393310546875
🎯 Target length (flattened): 65
🔁 CTC Loss: 3.70664119720459
🎯 Target length (flattened): 100
🔁 CTC Loss: 3.714085340499878
🎯 Target length (flattened): 94
🔁 CTC Loss: 3.6634626388549805
🎯 Target length (flattened): 42
🔁 CTC Loss: 3.6692681312561035
🎯 Target length (flattened): 88
🔁 CTC Loss: 3.7617032527923584
🎯 Target length (flattened): 56
🔁 CTC Loss: 3.6223487854003906
🎯 Target length (flattened): 97
🔁 CTC Loss: 3.7045013904571533
🎯 Target length (flattened): 24
🔁 CTC Loss: 4.505125522613525
🎯 Target length (flattened): 62
🔁 CTC Loss: 3.4829483032226562
🎯 Target length (flattened): 64
🔁 CTC Loss: 3.517364025115967
🎯 Target length (flattened): 76
🔁 CTC Loss: 3.4285190105438232
🎯 Target length (flattened): 72
🔁 CTC Loss: 3.5779104232788086
🎯 Target length (flattened): 67
🔁 CTC Loss: 3.3947243690490723
🎯 Target length (flattened): 69
🔁 CTC Loss: 3.7641541957855225
🎯 Target length (flattened): 58
🔁 CTC Loss: 3.4980602264404297
🎯 Target length (flattened): 16
🔁 CTC Loss: 5.133079528808594
🎯 Target length (flattened): 50
🔁 CTC Loss: 3.6803336143493652
🎯 Target length (flattened): 68
🔁 CTC Loss: 3.522111415863037
🎯 Target length (flattened): 62
🔁 CTC Loss: 3.3656301498413086
🎯 Target length (flattened): 55
🔁 CTC Loss: 3.6714768409729004
🎯 Target length (flattened): 66
🔁 CTC Loss: 3.5125913619995117
🎯 Target length (flattened): 50
🔁 CTC Loss: 7.875966548919678
🎯 Target length (flattened): 80
🔁 CTC Loss: 3.46755313873291
🎯 Target length (flattened): 70
🔁 CTC Loss: 3.3604953289031982
🎯 Target length (flattened): 75
🔁 CTC Loss: 3.4066619873046875
🎯 Target length (flattened): 102
🔁 CTC Loss: 3.7095465660095215
🎯 Target length (flattened): 79
🔁 CTC Loss: 3.6540136337280273
🎯 Target length (flattened): 100
🔁 CTC Loss: 3.7090768814086914
🎯 Target length (flattened): 58
🔁 CTC Loss: 3.463395595550537
🎯 Target length (flattened): 59
🔁 CTC Loss: 3.5960731506347656
🎯 Target length (flattened): 88
🔁 CTC Loss: 3.6000618934631348
🎯 Target length (flattened): 59
🔁 CTC Loss: 3.3780088424682617
🎯 Target length (flattened): 47
🔁 CTC Loss: 3.6539998054504395
🎯 Target length (flattened): 69
🔁 CTC Loss: 3.498924732208252
🎯 Target length (flattened): 56
🔁 CTC Loss: 3.3679862022399902
🎯 Target length (flattened): 49
🔁 CTC Loss: 3.6035027503967285
🎯 Target length (flattened): 57
🔁 CTC Loss: 3.511206865310669
🎯 Target length (flattened): 71
🔁 CTC Loss: 3.438486337661743
🎯 Target length (flattened): 52
🔁 CTC Loss: 3.5007855892181396
🎯 Target length (flattened): 100
🔁 CTC Loss: 3.5383529663085938
🎯 Target length (flattened): 38
🔁 CTC Loss: 3.6896660327911377
🎯 Target length (flattened): 95
🔁 CTC Loss: 3.4491121768951416
🎯 Target length (flattened): 81
🔁 CTC Loss: 3.464325189590454
🎯 Target length (flattened): 81
🔁 CTC Loss: 3.5103182792663574
🎯 Target length (flattened): 70
🔁 CTC Loss: 3.443812131881714
🎯 Target length (flattened): 74
🔁 CTC Loss: 3.482877254486084
🎯 Target length (flattened): 86
🔁 CTC Loss: 3.4168426990509033
🎯 Target length (flattened): 66
🔁 CTC Loss: 3.391951084136963
🎯 Target length (flattened): 70
🔁 CTC Loss: 3.3382911682128906
🎯 Target length (flattened): 88
🔁 CTC Loss: 3.3758909702301025
🎯 Target length (flattened): 105
🔁 CTC Loss: 3.541853427886963
🎯 Target length (flattened): 54
🔁 CTC Loss: 3.5241146087646484
🎯 Target length (flattened): 90
🔁 CTC Loss: 3.4183592796325684
🎯 Target length (flattened): 57
🔁 CTC Loss: 3.5900959968566895
🎯 Target length (flattened): 79
🔁 CTC Loss: 3.229950189590454
🎯 Target length (flattened): 63
🔁 CTC Loss: 3.434427261352539
🎯 Target length (flattened): 50
🔁 CTC Loss: 3.379427433013916
🎯 Target length (flattened): 58
🔁 CTC Loss: 3.5857601165771484
🎯 Target length (flattened): 115
🔁 CTC Loss: 3.4181504249572754
🎯 Target length (flattened): 69
🔁 CTC Loss: 3.4350991249084473
🎯 Target length (flattened): 53
🔁 CTC Loss: 3.7067174911499023
🎯 Target length (flattened): 87
🔁 CTC Loss: 3.2789018154144287
🎯 Target length (flattened): 95
🔁 CTC Loss: 3.3468613624572754
🎯 Target length (flattened): 85
🔁 CTC Loss: 3.2432522773742676
🎯 Target length (flattened): 75
🔁 CTC Loss: 3.368299961090088
🎯 Target length (flattened): 85
🔁 CTC Loss: 3.523646354675293
🎯 Target length (flattened): 52
🔁 CTC Loss: 3.4565811157226562
🎯 Target length (flattened): 96
🔁 CTC Loss: 3.294743537902832
🎯 Target length (flattened): 85
🔁 CTC Loss: 3.322690486907959
🎯 Target length (flattened): 86
🔁 CTC Loss: 3.2497150897979736
🎯 Target length (flattened): 37
🔁 CTC Loss: 3.7032151222229004
🎯 Target length (flattened): 61
🔁 CTC Loss: 3.462460517883301
🎯 Target length (flattened): 35
🔁 CTC Loss: 5.975278854370117
🎯 Target length (flattened): 64
🔁 CTC Loss: 3.213081121444702
🎯 Target length (flattened): 51
🔁 CTC Loss: 3.6794533729553223
🎯 Target length (flattened): 97
🔁 CTC Loss: 3.3052563667297363
🎯 Target length (flattened): 33
🔁 CTC Loss: 6.790470123291016
🎯 Target length (flattened): 78
🔁 CTC Loss: 3.3392505645751953
🎯 Target length (flattened): 83
🔁 CTC Loss: 3.490840196609497
🎯 Target length (flattened): 79
🔁 CTC Loss: 3.3681936264038086
🎯 Target length (flattened): 71
🔁 CTC Loss: 3.3416051864624023
🎯 Target length (flattened): 56
🔁 CTC Loss: 3.4072868824005127
🎯 Target length (flattened): 83
🔁 CTC Loss: 3.402491569519043
🎯 Target length (flattened): 58
🔁 CTC Loss: 3.3935956954956055
🎯 Target length (flattened): 48
🔁 CTC Loss: 3.5093202590942383
🎯 Target length (flattened): 76
🔁 CTC Loss: 3.433622360229492
🎯 Target length (flattened): 91
🔁 CTC Loss: 3.3585007190704346
🎯 Target length (flattened): 118
🔁 CTC Loss: 3.670778274536133
🎯 Target length (flattened): 86
🔁 CTC Loss: 3.3948159217834473
🎯 Target length (flattened): 81
🔁 CTC Loss: 3.3634142875671387
🎯 Target length (flattened): 52
🔁 CTC Loss: 3.4609475135803223
🎯 Target length (flattened): 69
🔁 CTC Loss: 3.2540104389190674
🎯 Target length (flattened): 83
🔁 CTC Loss: 3.5227489471435547
🎯 Target length (flattened): 50
🔁 CTC Loss: 7.30704927444458
🎯 Target length (flattened): 50
🔁 CTC Loss: 3.3533170223236084
🎯 Target length (flattened): 42
🔁 CTC Loss: 3.8801257610321045
🎯 Target length (flattened): 39
🔁 CTC Loss: 3.6790425777435303
🎯 Target length (flattened): 90
🔁 CTC Loss: 3.4968481063842773
🎯 Target length (flattened): 70
🔁 CTC Loss: 3.4207215309143066
🎯 Target length (flattened): 84
🔁 CTC Loss: 3.468719482421875
🎯 Target length (flattened): 75
🔁 CTC Loss: 3.3659400939941406
🎯 Target length (flattened): 49
🔁 CTC Loss: 3.503561019897461
🎯 Target length (flattened): 83
🔁 CTC Loss: 3.4509379863739014
🎯 Target length (flattened): 98
🔁 CTC Loss: 3.7262184619903564
🎯 Target length (flattened): 70
🔁 CTC Loss: 3.5625414848327637
🎯 Target length (flattened): 86
🔁 CTC Loss: 3.526401996612549
🎯 Target length (flattened): 61
🔁 CTC Loss: 3.293090343475342
🎯 Target length (flattened): 45
🔁 CTC Loss: 3.3019111156463623
🎯 Target length (flattened): 72
🔁 CTC Loss: 3.40706729888916
🎯 Target length (flattened): 49
🔁 CTC Loss: 3.333371639251709
🎯 Target length (flattened): 76
🔁 CTC Loss: 3.2309651374816895
🎯 Target length (flattened): 25
🔁 CTC Loss: 4.116089344024658
🎯 Target length (flattened): 81
🔁 CTC Loss: 3.3652184009552
🎯 Target length (flattened): 69
🔁 CTC Loss: 3.378408432006836

### Evaluation

In [ ]:
model_crnn.eval()
with torch.no_grad():
    for batch in test_loader:
        images = batch["images"].to(device)
        labels = batch["labels"]

        logits = model_crnn(images)  # [W, B, C]
        preds = logits.softmax(2).argmax(2).permute(1, 0)  # [B, W]

        for i, pred in enumerate(preds):
            decoded = tokenizer.decode(pred.cpu().numpy())
            target_text = tokenizer.decode(labels[i].cpu().numpy())
            print(f"📝 Predicted: {decoded}")
            print(f"✅ Actual   : {target_text}")
            print("----")
        break  # remove for full test set

## Language Detection

In [ ]:
import fasttext
import torch

# Detect the best available device
device = "cuda" if torch.cuda.is_available() else ("mps" if torch.backends.mps.is_available() else "cpu")
print(f"Using device: {device}")

# Ensure correct path to model file
model_path = "/Users/krishnanand/Documents/Git/Dependencies/lid.176.bin"  # Update this path if necessary
model = fasttext.load_model(model_path)

def detect_language(text):
    """Detect language of given text using FastText."""
    predictions = model.predict(text)
    lang_code = predictions[0][0].replace('__label__', '')
    return lang_code

text = "Bonjour, comment allez-vous?"
detected_lang = detect_language(text)
print(f"Detected Language: {detected_lang}")

## Summarization

In [ ]:
from transformers import pipeline
import torch

device = 0 if torch.cuda.is_available() else (0 if torch.backends.mps.is_available() else -1)

# Load summarization pipeline (T5-Base)
summarizer = pipeline("summarization", model="t5-base", device=device)

# Example input text
text = """
Artificial intelligence (AI) is the simulation of human intelligence processes by machines, especially computer systems.
These processes include learning, reasoning, and self-correction. AI is one of the most exciting and disruptive technologies
of our time, influencing everything from healthcare to transportation.
"""

# Generate summary
summary = summarizer(text, max_length=100, min_length=30, do_sample=False)
summary_text = summary[0]['summary_text']
print("Summary in English:", summary_text)

# Load translation pipeline with a better model
translator = pipeline("translation", model="Helsinki-NLP/opus-mt-en-es", device=device)

# Translate the summary
translated_summary = translator(summary_text)
print("Translated Summary in Spanish:", translated_summary[0]['translation_text'])

## Translator

In [ ]:
from transformers import pipeline
import torch

device = 0 if torch.cuda.is_available() else (0 if torch.backends.mps.is_available() else -1)

# Load the NLLB model for French to Hindi translation
translator = pipeline("translation", model="facebook/nllb-200-distilled-600M", device=device)

# Example French text
text = "Bonjour, comment allez-vous aujourd'hui?"

# Translate the text from French to English
translated_text = translator(text, src_lang="fra_Latn", tgt_lang="eng_Latn")
english_translation = translated_text[0]['translation_text']
print("Translated to English:", english_translation)

# Now, translate from English to Hindi
translated_to_hindi = translator(english_translation, src_lang="eng_Latn", tgt_lang="hin_Deva")
print("Translated to Hindi:", translated_to_hindi[0]['translation_text'])

## TTS

In [ ]:
from TTS.api import TTS
import torch

# Detect best available device (CUDA for NVIDIA, MPS for Apple Silicon, CPU as fallback)
device = "cuda" if torch.cuda.is_available() else ("mps" if torch.backends.mps.is_available() else "cpu")
print(f"Using device: {device}")

# Load a single-language English TTS model and move it to the selected device
tts = TTS("tts_models/en/ljspeech/tacotron2-DDC").to(device)

# Text to convert
text = ("The error 'Model is not multi-lingual but language is provided' means that "
        "the model does not support multiple languages. This model can only generate speech in English, "
        "so specifying language (French) is invalid.")

# Convert text to speech and save as an audio file
tts.tts_to_file(text=text, file_path="/Users/krishnanand/Documents/Git/Tests/test123.wav")

print("Speech synthesis complete! Output saved as 'test123.wav'.")

In [ ]:
pip install colabcode

In [ ]:
%pip install colabcode